### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by cjhowe** [tomaka/winit#100]
I noticed this issue on [glutin](https://github.com/tomaka/glutin/issues/29), and I think it applies to winit as well. I didn't see it get copied over, however, the build is definitely still broken. I'm currently working on a fork that fixes the build and adds full iOS support.

**Comment by cjhowe** [comment]
So, I noticed the use of setjmp/longjmp in the current iOS code, which led me to discover [this StackOverflow answer](http://stackoverflow.com/questions/2187684/how-can-i-remove-uiapplicationmain-from-an-iphone-application). It's quite a hack to use setjmp/longjmp to get around UIApplicationMain, and we're not sure Apple will be okay with that. SDL2 doesn't have this issue because they call out to the user's main function from within their AppDelegate. It's interesting to note that to build the iOS application with Rust in the first place, you have to add a main function directly to an XCode project that calls out to Rust through a static library. Is there some way to have the user's main function called from the AppDelegate only on iOS? Is that even possible to do from a dependency? How would it find the user's main function? This would also surely only apply to crates that aren't libraries, but it's hard to tell since from Rust's perspective iOS can only have libraries.

**Comment by cjhowe** [comment]
Actually, I'm not so sure calling main from the AppDelegate (which doesn't return) is any better than longjmp'ing out of the AppDelegate. I'm gonna work with the existing solution for now, unless anyone has a better idea.

**Comment by tomaka** [comment]
Please note that the current code is mostly a hack as far as I know. Only one person wrote it, and that person is probably the only one who ever tested it or knows how it works.
