### ISSUE TITLE
Duplicated keyboard events with dead keys in X11

### ISSUE THREAD

**Issue by siiptuo** [tomaka/winit#107]
When using [dead keys](https://en.wikipedia.org/wiki/Dead_key), for instance `´` and `a` to write `á`, in some keyboard layouts under X11, `ReceivedCharacter` event is fired twice:

```
KeyboardInput(Pressed, 21, None)
KeyboardInput(Released, 21, None)
ReceivedCharacter('á')
KeyboardInput(Pressed, 0, None)
ReceivedCharacter('á')
KeyboardInput(Pressed, 0, None)
KeyboardInput(Released, 38, Some(A))
```

This issue seems to be related to `XFilterEvent` which is [called in the code](https://github.com/tomaka/winit/blob/09e6698236bab971c2903df96e596ad770a94b2e/src/api/x11/input.rs#L134) but doesn't really do anything. Checking the return value and returning early if it's non-zero seems to fix this issue.

Other software [simply skip those events altogether](http://git.suckless.org/dmenu/tree/dmenu.c#n512) or do something [more](https://hg.libsdl.org/SDL/file/36f40b8cc979/src/video/x11/SDL_x11events.c#l566) or less [complicated](https://github.com/glfw/glfw/blob/master/src/x11_window.c#L906). In these examples filtering is also done for all events, not only in key events.

**Comment by wengxt** [comment]
Not checking the return value XFilterEvent is one issue, but the timing is also wrong.

To support input method and compose correctly, the XFilterEvent should be called immediately after XNextEvent, and check the return value there.

https://github.com/tomaka/winit/blob/master/src/platform/linux/x11/window.rs#L176

XFilterEvent should be called right here.

I used to fix input method bug in some other Xlib app, for more details just check the comment I added in following links.

http://git.suckless.org/st/commit/?id=5f48e89716a74e75b6040fdb067372180626b699
