### ISSUE TITLE
Improve keyboard event handling

### ISSUE THREAD

**Issue by rigtorp** [tomaka/winit#108]
Winit / Glutin is used by the Rust terminal emulator Alacritty (https://github.com/jwilm/alacritty). It requires some improvements to the keyboard event handling and is using a fork of glutin (https://github.com/jwilm/glutin) with these improvements (https://github.com/jwilm/glutin/commits/keyboard-mods).

Would you be interesting in merging these changes after they have been reworked for latest version of winit?

**Comment by Ralith** [comment]
This was fixed by #112 and #164, right? Can the issue be closed?

**Comment by jwilm** [comment]
Yeah, this is fixed.
