### ISSUE TITLE
Would it make sense to add a way to maximize the window?

### ISSUE THREAD

**Issue by pedrocr** [tomaka/winit#129]
Windowing systems often have a WM hint or similar mechanism to get the operating system to resize the window to it's maximum dimensions on the screen. Would adding this to the Window API make sense?

**Comment by francesca64** [comment]
Thanks to #457, this is now implemented on Windows.

**Comment by francesca64** [comment]
This was also implemented on Wayland back in #383.

**Comment by francesca64** [comment]
With #465, this is now implemented everywhere.
