### ISSUE TITLE
Add method to close window

### ISSUE THREAD

**Issue by humb1t** [tomaka/winit#13]
You provided a possibility to create/show/hide/resize window:
`pub fn hide(&self) {
        self.window.hide()
}`
But I sure that 'pub fn close' method is also can be provided.

**Comment by LFalch** [comment]
Can't you just drop the object?

**Comment by humb1t** [comment]
Yes, I can. But this is not the same.

**Comment by francesca64** [comment]
@humb1t in what way should it be different?

**Comment by Osspial** [comment]
It looks like the consensus as per #434 is that we aren't going to add a `close` method, so I'm going to close this issue.
