### ISSUE TITLE
Add #[derive(Eq, PartialEq, Hash)]] winit::Event

### ISSUE THREAD

**Issue by unpatched** [tomaka/winit#134]
Any objection to this?  I'm trying to handle input events with HashMap entries and the Key entry requires those three Traits.

**Comment by tomaka** [comment]
There's no problem with that.

**Comment by unpatched** [comment]
Perfect, I will get a PR rolling. Thank you.

**Comment by tomaka** [comment]
Winit just got a major breaking change and won't get any new version for a while.
If you want this change to be in quickly, you should create a commit against https://github.com/tomaka/winit/commit/56b536cd4818550f4bbfb295aeaed60c7ce30b45 and ask me here to create a branch where to submit the PR.

**Comment by unpatched** [comment]
It turns out the floats in the Events bring about some problems when you need to implement Eq.  This is probably the reason it is not already implemented.  Closed, but thank you.
