### ISSUE TITLE
Publishing the new API to crates.io?

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/winit#139]
@tomaka just thought I'd open an issue for tracking progress towards this. What needs to be done before winit is ready to publish the new API? In your last comment on #126 you mentioned this:

> The next steps are to write a PR that panics if we call a callback from within a callback, and to update the backends.

Are you waiting to solve both of these before updating?

I'm mainly curious as I'd like to have a go at updating glutin to the latest changes so that I can use them within my own projects, however if there's anything I can do to move things along with winit I'd prefer to help here first.

**Comment by tomaka** [comment]
Well, the idea was to make sure there's no problem in the API and to make last minute changes if needed.

**Comment by mitchmindtree** [comment]
Closed by #142.

**Comment by mitchmindtree** [comment]
Ah my mistake, I thought #142 was against master but it was against a previous commit!

**Comment by mitchmindtree** [comment]
Sorry to bother @tomaka, I have a small amount of free time coming up and would like to begin working on updating `glutin` to the recent API changes, however I'd like to get confirmation that these changes will be published first. Any chance you're ready to go ahead with publishing?

**Comment by tomaka** [comment]
@mitchmindtree People who I've known for some time will never bother me ;)

The only reason why I'm hesitating to publish a version is that `wait_events()` is implemented with a spinlock on win32 and linux. But if you need it for glutin, I'm going to publish it anyway.

**Comment by mitchmindtree** [comment]
Closed by #147
