### ISSUE TITLE
Breaking dependency `wayland-window`

### ISSUE THREAD

**Issue by TomboFry** [tomaka/winit#145]
The library `wayland-window` was recently updated from 0.4.2, as specified in this library, to 0.4.5. Version 0.4.5 depends on a new release of the `wayland-client` library version 0.8.0, which as specified by the author has [breaking changes](https://github.com/vberger/wayland-client-rs/releases/tag/v0.8.0). This means that their use of semantic versioning has broken this library.

Due to this, I am unfortunately unable to compile any project that depends on this library.

A very temporary solution to the problem would be to update the version number of wayland-window in the Cargo.toml file from `"0.4.2"` to `"=0.4.2"`, however the underlying breaking changes in wayland-client would still reside in all later versions of its parents' libraries.

**Comment by ebkalderon** [comment]
I am running into this problem as well.

**Comment by ebkalderon** [comment]
The offending version of the library has been yanked for now. I think this issue can be closed.

**Comment by TomboFry** [comment]
Ah, thank you very much!
