### ISSUE TITLE
How to wakeup the event loop on mac?

### ISSUE THREAD

**Issue by paulrouget** [tomaka/winit#166]
With the new event loop mechanism, how can I wake up the event loop from a different thread?

In the past, I could use `WindowProxy::wakeup_event_loop()`, but apparently, `create_window_proxy` is gone on mac.

**Comment by mitchmindtree** [comment]
@paulrouget `EventsLoop` can be shared across threads (behind an `Arc`), so you should be able to call `EventsLoop::interrupt` from the different thread.

**Comment by paulrouget** [comment]
Indeed. It works. Thank you.
