### ISSUE TITLE
Window example on wayland creates 0x0 pixels window

### ISSUE THREAD

**Issue by Vinatorul** [tomaka/winit#17]
It looks like `winit` doesn't resize wayland window after start (`resize_callback` function have not been called).
I've checked `glutin` example on wayland and it works well. Then I checked the difference beetween `api/wayland/window.rs` in `winit` and `glutin` and found out that there is no `resize` calls in `winit`. For example: [glutin](https://github.com/tomaka/glutin/blob/master/src/api/wayland/window.rs#L79) and [winit](https://github.com/tomaka/winit/blob/master/src/api/wayland/window.rs#L73). It seems to me that there should be some code to resize `surface`, but I haven't find any API in `wayland-client` to do so.

**Comment by tomaka** [comment]
cc @vberger

**Comment by tomaka** [comment]
From my knowledge of wayland, the size of the surface of a wayland window is actually determined by the OpenGL or Vulkan context that uses it. Since winit doesn't create an OpenGL/Vulkan context, it has no way to set the size.

Maybe that should be more explicit in winit.

**Comment by vberger** [comment]
Yes, on wayland, the size of a surface is defined by the size of the buffer associated to it.

In case of glutin, the `resize` method is a method provided by the EGL layer, to define the size of the OpenGL surface (I expect vulkan should provide some similar API).

In an opengl-less wayland case, the size of a surface is defined by the size of the `wl_buffer` associated to it. If no buffer is associated, the surface is 0 by 0.

**Comment by Vinatorul** [comment]
@tomaka, @vberger thanks for the explanations.
So for wayland I will need to override most of the methods only to add EGL calls where necessary?

**Comment by vberger** [comment]
Regarding wayland, if you want to do EGL stuff without glutin, you'll need to use the `egl` module (and feature) of `wayland-client`. The `WlEglSurface` provides a method to be resized, and you need to then provide it to EGL initialization routines.

However, I've just recently completely rewrote the API of wayland-client, and not yet upgraded winit and glutin to it (but I'm working on it), so you might want to wait until it's done. I'll probably rethink details of wayland on winit on the process.

**Comment by Vinatorul** [comment]
I forget to mention - I faced with it while working on tomaka/glutin#813
I am using `egl`, and create window via `winit`, but it seems I should wrap some  `winit::wayland::Window` methods to add `egl` calls, for example [set_inner_size](https://github.com/tomaka/winit/blob/master/src/api/wayland/window.rs#L230) or [next_event](https://github.com/tomaka/winit/blob/master/src/api/wayland/window.rs#L35)

**Comment by tomaka** [comment]
@Vinatorul You need to wrap everything anyway, not only for wayland.

**Comment by Vinatorul** [comment]
Thanks for answers. I'll close this issue as it works as intended.
