### ISSUE TITLE
Add EventsLoop::wakeup independent of interrupt

### ISSUE THREAD

**Issue by jwilm** [tomaka/winit#175]
The method `EventsLoop::interrupt()` is currently serving the dual purpose of

1. Stop processing events during `run_forever` and `poll_events`
2. Wakeup the event loop from other threads

Running the wakeup code when you only care about 1. simply wastes cycles.

I'm proposing that a second method, `EventsLoop::wakeup()` is added to allow performing these tasks independently. An alternative design would be removing the `interrupted` flag altogether and allow the closure passed to `run_forever` and `poll_events` to *return* a flag indicating their desire to continue or halt.

**Comment by jwilm** [comment]
Btw, I'd be happy to implement this. I thought discussion was an appropriate first step, though.

**Comment by jwilm** [comment]
I've thought about this a bit more, and I think it would be appropriate for the `wakeup` method to take a `winit::WindowId` so that the Awakened event is associated with the correct window.

**Comment by jwilm** [comment]
Digging into the source a bit, it looks like there's some leftover `WindowProxy` implementations. These aren't available in the public API anymore since the recent event handling refactor. Seems like they should be removed / be absorbed into `EventsLoop::wakeup` implementations.

**Comment by jwilm** [comment]
Does anyone have feedback about this?

**Comment by mitchmindtree** [comment]
@jwilm just thought I'd let you know that #136 and in particular [this comment](https://github.com/tomaka/winit/pull/136#issuecomment-303082720) are related to (and probably supersede) this.

**Comment by jwilm** [comment]
Agreed that the pending `Proxy` type should supersede this.
