### ISSUE TITLE
EventsLoop doesn't implement Clone?

### ISSUE THREAD

**Issue by icefoxen** [tomaka/winit#177]
`EventsLoop` contains an `Arc`, and it seems like the obvious way to be able to share it among multiple threads would be to `Clone` it.  But it doesn't implement `Clone`.  Is this intentional, or an oversight?

Thanks in advance.

**Comment by jwilm** [comment]
`EventsLoop` API is `Sync`. You can wrap it in an `Arc` in your application code.

**Comment by icefoxen** [comment]
Yeah, but it *already* contains an `Arc` and only an `Arc`.  Adding another seems redundant.  :-P

**Comment by jwilm** [comment]
Oh, you're talking about the newtype struct. Yeah, seems like it would make sense.

**Comment by jwilm** [comment]
Alternatively, maybe the arc in the wrapper struct should just be removed. Forcing the application to wrap it in an Arc dispels any illusion of having anything other than multiple references to the same event loop.

**Comment by tomaka** [comment]
The reason why it contains an Arc is so that methods implemented on `EventLoop` can "clone" the event loop as well.

The reason why Clone isn't implemented is a mistake though.
