### ISSUE TITLE
Add Change log

### ISSUE THREAD

**Issue by LPGhatguy** [tomaka/winit#183]
There is no change log for this project, and figuring out what exactly has broken in the latest release when I'm trying to upgrade code is difficult.

Would there be interest in adding a `CHANGELOG.md` file to both this repository and glutin, too?

**Comment by tomaka** [comment]
The problem is that in my opinion it is worse to have an unmaintained CHANGELOG.md than to not have one at all.

**Comment by LPGhatguy** [comment]
Do you think that there's enough value in having a _maintained_ `CHANGELOG.md` to warrant the risk?

**Comment by kaedroho** [comment]
+100

I find maintaining projects significantly easier when the dependencies have a changelog. Changelogs are a great way of incentivising users to upgrade and guiding them when an API breakage occurs.

IMO, I would actually call it *the most* important part of the documentation. Without it, few people will know what new features have been added, what bugs have been fixed and the names of who spent their time making those changes. The only alternatives are to either to subscribe for issues updates or read the commit log (which are both quite noisy and not written in an end user centric way).

**Comment by LPGhatguy** [comment]
Hey, there's a change log now!
