### ISSUE TITLE
`EventsLoop::interrupt` does not interrupt a blocking call to `dispatch` during `run_forever`

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/winit#189]
Currently, the interrupt method only causes the loop to break when the next event is dispatched. The correct behaviour would be to cause the inner `dispatch` call to immediately stop blocking (it should not wait until the next event is received).

@vberger I'm unsure how to do this with wayland, any ideas? Perhaps there's a hint in the old `WindowProxy` code in pre-6.0.0 winit. It'd be nice if we could work this out before working on #187.

**Comment by mitchmindtree** [comment]
It looks like the old wayland `WindowProxy` code used to call [this WlDisplay method](https://docs.rs/wayland-client/0.9.4/wayland_client/protocol/wl_display/struct.WlDisplay.html#method.sync) via the WaylandContext. After trying it out, this alone does not seem cause a break from `dispatch`. The docs do however mention that it causes a `done` event to be emitted. Perhaps this means we have to implement [this trait](https://docs.rs/wayland-client/0.9.4/wayland_client/protocol/wl_callback/trait.Handler.html#method.done) for `InputHandler` and use it to break from the loop if `interrupt` was called?

**Comment by vberger** [comment]
You'd also need to make a call to WaylandContext::flush() so that the sync event is effectively sent to the server. Whithout that, we would never receive the "done" event to would unlock the blocking call.

**Comment by mitchmindtree** [comment]
@vberger ahh thanks for the tip, I've got this working in #191.

**Comment by jwilm** [comment]
Can this be closed now that #191 landed?
