### ISSUE TITLE
Win32: with_dimensions excludes decoration, with_max_dimensions includes them

### ISSUE THREAD

**Issue by LPGhatguy** [tomaka/winit#196]
I have a reproduction case [here that works with the latest master.](https://gist.github.com/LPGhatguy/8d12e3a9e0fad838a881f200e3687c6c)

It looks like, on Win32 at least, `with_max_dimensions` and `with_min_dimensions` include the window decorations, but `with_dimensions` does not. Only including the client area seems like the correct approach here, so this seems like a bug.

I'm taking a look at this.

**Comment by BonsaiDen** [comment]
Running into the same issue here, below are a two comparison screenshots.

Ubuntu (640x480 as set / expected):

![ubuntu](https://cloud.githubusercontent.com/assets/124674/26799839/65bace74-4a37-11e7-9a0a-226a0cc4c744.png)

Windows 10 (Too small ):

![win10](https://cloud.githubusercontent.com/assets/124674/26799827/5947723c-4a37-11e7-8595-1966850f2367.png)

**Comment by LPGhatguy** [comment]
After a discussion with @tomaka a few days ago in IRC, it sounds like this behavior just isn't well-defined.

Someone should propose a documentation update to specify the correct behavior here (probably just including client area, and using client units?) and then update the backends to match it.

**Comment by Torwegia** [comment]
https://github.com/tomaka/winit/blob/cfd087d9a5213305175ec97b7028ea55360d4cff/src/platform/windows/window.rs#L372

Does that if statement need to be inverted?

**Comment by Dooskington** [comment]
I am also having the same issue - any updates?

**Comment by francesca64** [comment]
@Dooskington today is a happy day, for this is now fixed in master.
