### ISSUE TITLE
X11 - For both DeviceEvent and WindowEvent, KeyboardInput ModifiersState fields are always false

### ISSUE THREAD

**Issue by rukai** [tomaka/winit#226]
WindowEvent caused by:
https://github.com/tomaka/winit/commit/0b75a6b60c63ecee0e55c552c83813e517ad4b5c

DeviceEvent:
Never implemented for this case

I'll have a PR for it today or tomorrow.

**Comment by francesca64** [comment]
Closing in favor of #483
