### ISSUE TITLE
Missing events for Window(surface) creation/release

### ISSUE THREAD

**Issue by zpgaal** [tomaka/winit#240]
It seems as there is no way to get notified of the window creation/destruction.
I'm using glutin and the events are based on the winit events.
I need a way to create hw resources when the window is created, and do some cleanup before destroy.

To be more clear: on windows  is there any way to get events/handle/notifictions of the WM_CREATE and WM_CLOSE os events?
(WM_DESTROY which triggers the Closed Event  is too late for me)

Thanks

**Comment by tomaka** [comment]
`WM_CLOSE` is reported as `Closed`, but `WM_CREATE` isn't available unfortunately.

**Comment by zpgaal** [comment]
Only WM__DESTROY is handled which is called after the window's been closed.

```
pub unsafe extern "system" fn callback(window: winapi::HWND, msg: winapi::UINT,
                                       wparam: winapi::WPARAM, lparam: winapi::LPARAM)
                                       -> winapi::LRESULT
{
    match msg {
        winapi::WM_DESTROY => { 
...
```

MSDN:
Sent when a window is being destroyed. It is sent to the window procedure of the window being destroyed after the window is removed from the screen.

By this time the GL context is released by the OS. But please correct me if I'm wrong. [ex see](https://www.khronos.org/opengl/wiki/Platform_specifics:_Windows#When_do_I_destroy_the_GL_context.3F)

**Comment by zpgaal** [comment]
PR sent : https://github.com/tomaka/winit/pull/246

**Comment by zpgaal** [comment]
Alternative solution PR: https://github.com/tomaka/winit/pull/247

**Comment by zpgaal** [comment]
I think it can be closed now.
