### ISSUE TITLE
0.7.6

### ISSUE THREAD

**Issue by NeQuissimus** [tomaka/winit#264]
When do you plan on releasing 0.7.6 into Crates? I'd like to use a stable release that has `send_xim_spot` on `Window`.

Thank you :)

**Comment by tomaka** [comment]
@NeQuissimus Just open a PR that bumps the version in the Cargo.toml.

**Comment by NeQuissimus** [comment]
@tomaka Well, that's easy enough :D Wasn't sure whether you had some sort of roadmap...
