### ISSUE TITLE
X11 window is renamed after creation

### ISSUE THREAD

**Issue by carado** [tomaka/winit#282]
In X11, using the window builder with with_title creates the window without a title and then very shortly after renames the window as it should.

The problem with that is that my window manager (i3) chooses on which desktop to open windows and whether to put them in floating mode based on their name, and sometimes it catches the window's name before it is changed, causing the window to briefly appear (in my case) in non-floating mode and then immediately after to go in floating mode (as it should be from the start); but the brief non-floating period can mess up other windows opened on the same desktop in i3.

I realize this is a very minor and specific nitpick, but I don't have that problem developing with GLFW, so surely it's possible to set a window's name directly as it is created on X11.

(I was redirected here from https://github.com/tomaka/glutin/issues/932 )

**Comment by francesca64** [comment]
It's actually not possible to set the title prior to window creation, but [ICCCM](https://www.x.org/docs/ICCCM/icccm.pdf) section 4.1.2 tells us:
> The window manager will examine the contents of these properties when the window makes the
transition from the Withdrawn state and will monitor some properties for changes while the window
is in the Iconic or Normal state.

The window makes that transition when we call `XMapRaised`, so fixing this should simply be a matter of setting the title before that.

[I've created a branch with that change](https://github.com/francesca64/winit/tree/x11-earlier-title). If you try using it, does it resolve your problem?

**Comment by carado** [comment]
Hi, sorry for the delay in answering. The change indeed solves the problem (as tested with the winit examples), thanks !

**Comment by tomaka** [comment]
Great, Thanks!
