### ISSUE TITLE
Numpad keys are not getting detected.

### ISSUE THREAD

**Issue by jojolepro** [tomaka/winit#287]
I had the issue on both piston engine and amethyst, so I guess its cause by their common dependency: winit.
Here's the result of xev:
```
KeyPress event, serial 33, synthetic NO, window 0x4a00001,
    root 0x219, subw 0x0, time 15329341, (-270,304), root:(701,358),
    state 0x10, keycode 52 (keysym 0x7a, z), same_screen YES,
    XLookupString gives 1 bytes: (7a) "z"
    XmbLookupString gives 1 bytes: (7a) "z"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x4a00001,
    root 0x219, subw 0x0, time 15329405, (-270,304), root:(701,358),
    state 0x10, keycode 52 (keysym 0x7a, z), same_screen YES,
    XLookupString gives 1 bytes: (7a) "z"
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x4a00001,
    root 0x219, subw 0x0, time 15331701, (-270,304), root:(701,358),
    state 0x10, keycode 88 (keysym 0xffb2, KP_2), same_screen YES,
    XLookupString gives 1 bytes: (32) "2"
    XmbLookupString gives 1 bytes: (32) "2"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x4a00001,
    root 0x219, subw 0x0, time 15331741, (-270,304), root:(701,358),
    state 0x10, keycode 88 (keysym 0xffb2, KP_2), same_screen YES,
    XLookupString gives 1 bytes: (32) "2"
    XFilterEvent returns: False
```
No event gets fired for the numpad keys (numlock on or off, doesn't matter)

Thanks!

**Comment by francesca64** [comment]
Do you have this problem when running one of the examples? i.e.
```bash
git clone https://github.com/tomaka/winit.git
cd winit
cargo run --example window | grep KeyboardInput
```
I'm not able to reproduce this, so the problem could be somewhere else.

**Comment by jojolepro** [comment]
I don't have the issue on my new computer (Arch). I originally had the issue on my laptop(Ubuntu), but I'm having trouble with it these days (won't connect to the wifi + randomly freezes) so I didn't test with it. Sorry for the delay, I rarely check github notifications(too many) ;)

**Comment by francesca64** [comment]
Well, since:
- Neither of us can reproduce this
- We can't verify that this was due to winit
- The relevant code has changed since this was opened

I'd like to consider this closed. Feel free to re-open if you find that it's still a problem, and I'll do my best to help you.
