### ISSUE TITLE
Dependency on XFree86-VidModeExtension fails with remote X, Wayland

### ISSUE THREAD

**Issue by AaronFriel** [tomaka/winit#291]
As described in title, I'm finding that virtually no Rust compiled window applications work with a setup that otherwise works perfectly for me: X remoting from a virtual machine or Windows Services for Linux to a host X server.

Using this set up I can run:

* Visual Studio Code
* Atom
* Chrome
* Firefox
* Hyper / xterm.js / etc.
* Other OpenGL API using applications (e.g.: xgears)
* Virtually anything

But I cannot run:

* alacritty
* piston
* conrod
* amethyst
* et al.

Since virtually the entire Rust graphical application ecosystem depends on `winit` and `glutin` to draw windows, I get errors like this:

```
friel@Ziggurat:/mnt/x/c/gh/alacritty$ cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.31 secs
     Running `target/release/alacritty`
Xlib:  extension "XFree86-VidModeExtension" missing on display ":0.0".
Alacritty encountered an unrecoverable error:

        There was an error initializing the shaders: failed compiling shader:
```

**Comment by Ralith** [comment]
Is this still true with winit 0.8? I think we removed any actual use of that extension with https://github.com/tomaka/winit/pull/270.

**Comment by AaronFriel** [comment]
That's wonderful to hear! Is winit 0.8 published?

**Comment by vberger** [comment]
It was a few hours ago. 😉

**Comment by AaronFriel** [comment]
Awesome, I pulled `winit` and used the Cargo patch feature to use it to build `alacritty` and I'm getting build errors in `glutin`, is that expected?

**Comment by tomaka** [comment]
> is that expected?

Winit 0.8 contains breaking changes, so yes.

**Comment by francesca64** [comment]
@AaronFriel can this issue be closed?
