### ISSUE TITLE
keyboard scancodes inconcsistencies between X11 and Wayland

### ISSUE THREAD

**Issue by vberger** [tomaka/winit#293]
Wayland forwards the raw keycodes (meaning `ESC` is 1, `1` is 2, `2` is 3, etc...), while X11 forwards them with a constant `+8` offset. This is apparently something known about keymap handling:

See [the xkbcommon documentation](https://github.com/xkbcommon/libxkbcommon/blob/master/doc/keymap-format-text-v1.md):
> Note that in all current keymaps there's a constant offset of 8 (for historical reasons).

What should we do to be consistent?

- Should the wayland backend  add the +8 offset?
- Should the X11 backend remove it?

Is there a way we can compare to the other backends?

**Comment by Ralith** [comment]
Shouldn't people be treating codes as opaque? I don't have any objections to doing this (I'd favor subtracting X's offset) but I'm not sure of the benefit. I guess it'd make it easier to hardcode sane default keybinds if you're willing to assume specific keyboard hardware?

**Comment by tomaka** [comment]
Scan code should be treated as opaque, but you'd expect that they more or less depend on the keyboard, especially considering that technically the scan code is the raw value sent by the keyboard itself. I would be surprised if all the scan codes changed when switching between Wayland and X.

**Comment by vberger** [comment]
The reason we stumbled on this is in the context of smithay: we are only using the raw key values and actually doing the keymap interpretation ourselves. And on Linux, these keycodes don't actually depend on the keyboard, but are pretty well defined (see [here](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L63) ).

Though I can understand if this does not fall under a supported use-case of winit.

**Comment by Ralith** [comment]
It seems like it'd be nice for e.g. user-configured keybindings to not break if you upgrade your system from X11 to Wayland. We can't realistically provide that across platforms in general, but I'm not opposed to doing so here considering how trivial a fix it is.
