### ISSUE TITLE
Move `hidpi_factor` to MonitorId

### ISSUE THREAD

**Issue by jwilm** [tomaka/winit#315]
This would allow the device-pixel-ratio to be determined before creating a window. Alacritty's use case for this is showing a correctly dimensioned window at startup without having a flash of the incorrectly sized window. This is because terminal size is usually dictacted by lines/columns requested, and that requires the scale factor to compute.

**Comment by kryptan** [comment]
Do you want to remove `hidpi_factor` from `Window`? I think it should be in both `Window` and `MonitorId`.  You could have `Window` which is scaled by OS and thus has different `hidpi_factor` than the monitor it is located at.

**Comment by vberger** [comment]
Has #319 Solved this?

**Comment by jwilm** [comment]
I guess that depends on the definition of solved. #319 just stubbed out methods on MonitorId rather than implement them.
