### ISSUE TITLE
X11 doesn't like creating and destroying a lot of windows

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#32]
Original: https://github.com/tomaka/glutin/issues/89

**Comment by bvssvni** [comment]
Could this be caused by https://github.com/PistonDevelopers/piston_window/issues/215#issuecomment-343635266 ?

> @bvssvni looks to be happening in the winit's X11 window destructor. PoisonError is for mutex being locked twice without unlocking. I suggest filing an issue to winit.

cc @kvark

**Comment by tomaka** [comment]
No, this is unrelated. I just realized that this issue doesn't give any detail. Creating and destroying lots of windows caused a segfault if I remember correctly, and not a Rust panic. But since the X11 backend has received a lot of changes over time, someone should check if it can still be reproduced.

**Comment by bvssvni** [comment]
I opened up a new issue https://github.com/tomaka/winit/issues/347

**Comment by francesca64** [comment]
Opening and closing 100 windows in rapid succession seems to be fine. As for the original repro of calling `cargo test` with glium, that SIGSEGVs as soon as it hits the framebuffer tests, though I'm not sure if it's related.
