### ISSUE TITLE
More granular control over decorations on WindowBuilder

### ISSUE THREAD

**Issue by sodiumjoe** [tomaka/winit#323]
Per https://github.com/jwilm/alacritty/issues/686 and https://github.com/jwilm/alacritty/issues/168

iterm2 and Atom both allow customizations of the titlebar. It would be nice to have more granular control over:

* hide titlebar without removing borders and resize controls
* background color
* foreground color

**Comment by vberger** [comment]
How would other platform allow it?

For wayland there is not technical block, as we are drawing the decorations. It's "just" a matter of implementing in in wayland-window.

**Comment by PaperPrototype** [comment]
So has this been implemented yet?

**Comment by PaperPrototype** [comment]
Never mind. https://github.com/rust-windowing/winit/pull/389
