### ISSUE TITLE
winit brings in two versions of core-foundation

### ISSUE THREAD

**Issue by branan** [tomaka/winit#329]
`winit` itself depends on `core-foundation 0.4` and `core-graphics 0.8`, but that version of `core-graphics` depends on `core-foundation 0.3`. Presumably the right fix is to try to rev `core-graphics` to a more recent version, but I don't have a mac environment to do this work in. I just noticed the duplicate `core-foundation` crate when auditing the dependencies of one of my projects.

**Comment by sodiumjoe** [comment]
this appears to have been fixed by #335, can we close?

**Comment by branan** [comment]
The dependencies of winit look clean now. Vulkano-win is now pulling in multiple versions of OSX libs (some via winit), but that's a different issue I need to file against that repo
