### ISSUE TITLE
Expose mouse pos

### ISSUE THREAD

**Issue by stuartnelson3** [tomaka/winit#348]
I'm currently in the process of un-forking glutin in servo. The [last issue](https://github.com/servo/servo/pull/19120#issuecomment-343713605) preventing this is that `WindowEvent::MouseInput` and `WindowEvent::MouseWheel` do not provide the mouse's current position.

Since mouse moved events are only received when the window is focused, this makes it possible for a the window to lose focus, the user can move the mouse, and then the window regains focus with its last known mouse position being incorrect. For an application that depends on knowing the mouse position to handle mouse events in different ways, this results in incorrect behavior.

I have two ideas on how to fix this:

1. Expose the mouse position information on `WindowEvent::{MouseInput, MouseWheel}`, or
2. Expose the mouse position information on `WindowEvent::Focus` (I'll admit this option feels a bit weird, but it could also work).

Do either of these sound like potential options? I would be happy to implement this.

**Comment by vberger** [comment]
A third option would be to ensure that whenever the window gains pointer focus, a `MouseMoved` event would be sent after the `MouseEntered` or `Focus` event.

**Comment by stuartnelson3** [comment]
That sounds like the simplest solution -- no need to modify the exposed api

**Comment by stuartnelson3** [comment]
Opened a PR, perhaps it's a solution
