### ISSUE TITLE
ReceivedCharacter event not emitted for delete key on Windows

### ISSUE THREAD

**Issue by Xaeroxe** [tomaka/winit#350]
I guess the Windows API doesn't consider delete to be a character, whereas X11 does.  This can cause code to handle text deletion to work well on Linux but not on Windows.  So in order to provide better cross platform guarantees maybe we should emit a CharacterReceived event with Unicode character 7F when the delete key is pressed on Windows.

No testing has been done on OSX for this yet.

**Comment by Ralith** [comment]
I don't think you should be implementing text deletion UI by inspecting the unicode code points you receive in the first place. We certainly shouldn't be presuming to know better than the OS keymap...

**Comment by Xaeroxe** [comment]
Inspecting unicode code points to some degree is necessary as back-ends emit all kinds of non-printable nonsense you wouldn't want in a UI string.

In my code I ask my text entry to ignore characters with hexcode 0-7 and E-19.  I think it's perfectly reasonable to assume we know better than the OS keymap because it does a lot of strange things that aren't applicable in the modern world.

Regardless of whether you agree with my way of implementing that or not, this is still a way to accomplish the task that works on Linux and doesn't on Windows.  It's a platform inconsistency in a library that promises platform consistency as far as is reasonable.

**Comment by Xaeroxe** [comment]
When researching the issue I discovered a general sentiment among C and C++ programmers that not emitting the delete character was a mistake from Microsoft.  Microsoft can't fix this because they'd risk breaking existing code that isn't expecting these delete characters, but we have the opportunity to fix it for us, because there is very little code written that is expecting these to be omitted.
