### ISSUE TITLE
Glutin window is not receiving Drag&Drop events

### ISSUE THREAD

**Issue by Boscop** [tomaka/winit#353]
My glutin 0.9.2 (winit 0.7.6) window is not receiving any DroppedFile, HoveredFile, or HoveredFileCancelled events on Win 8.1. 

Is it working for anyone else on Windows?

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by francesca64** [comment]
I've just realized that winit 0.7.6 is *ancient*. Though, `DroppedFile` was apparently implemented on Windows 3 years ago (826931e2c2e61ec7815d25ec33618bfe4aacff0d) so it might not make a difference. Either way, do you still have the problem running a recent version of winit (0.11 or later)?

**Comment by francesca64** [comment]
Closing this, both due to my previous comment and the implementation for `DroppedFile` changing in #662.
