### ISSUE TITLE
Some types of events do not wakeup run_forever()

### ISSUE THREAD

**Issue by mikedilger** [tomaka/winit#356]
If I have a separate thread making Vulkan calls that calls `get_surface_capabilities_khr()`, that call doesn't return until some OTHER event (e.g. mouse movement) wakes up the EventsLoop.

Is this already known? ~~Is there a workaround? Should I be structuring my code differently?~~

edit: I'm working around it with poll_events().

**Comment by tomaka** [comment]
I'm not sure if I understand correctly. If you're expecting Vulkan to wake up the events loop, then no it's not possible.

**Comment by mikedilger** [comment]
Ok thanks.
