### ISSUE TITLE
Will winit call `DestroyWindow` twice?

### ISSUE THREAD

**Issue by LYP951018** [tomaka/winit#384]
I saw that winit posts `WM_CLOSE` in `Window`'s `drop` method, and `DefWindowProcW` calls `DestroyWindow` internally when handling `WM_CLOSE`. Then the `drop` method for `WindowWrapper` calls `DestroyWindow` again? Did I understand something wrongly?

**Comment by GabrielMajeri** [comment]
Can confirm the bug, added an assertion and it got triggered. Will follow up with a pull request to fix this shortly.
