### ISSUE TITLE
No backend is available

### ISSUE THREAD

**Issue by linde12** [tomaka/winit#392]
Hello! I'm running Debian Jessie 8.10 with kernel 3.16.0-5-amd64. I'm unable to run the examples of winit. I get the following output:

```
~/D/winit (master) » env RUST_BACKTRACE=1 cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/window`
thread 'main' panicked at 'No backend is available', src/platform/linux/mod.rs:340:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:537
   6: winit::platform::platform::EventsLoop::new
             at src/platform/linux/mod.rs:340
   7: winit::EventsLoop::new
             at src/lib.rs:195
   8: window::main
             at examples/window.rs:4
   9: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  13: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: <unknown>
```

I'm using nvidia drivers version 340.102 and other X programs work fine. I run awesome WM as window manager and i've tried running glxgears and it runs. I don't understand why winit won't run for me. Any help appreciated.

**Comment by b-r-u** [comment]
I see the same backtrace on Debian with the Mesa driver. Originally, I was using winit through the glutin crate and could fix this issue by switching to the servo-glutin crate (an older fork by the servo team). It would be interesting to see the change in winit, glutin or servo-glutin that made the difference here.

**Comment by b-r-u** [comment]
I have tested several commits and it seems a commit from last September (59c33d2c6a804a8a1e2c16416ef7448e679b0b58) introduced this behavior:
* 136d3beed117df96364e6537ac467b47136d8541 0.5 works
* e196f80e988cb06012e67910c048db12bb91960d 0.7.1 works
* be9d4e7e03c9b37d50868c129199564b4efb7517 0.7.6 works
* 342d5d8587d96bec804ef45f3f7d6abec950e826 (2017-09-06) works
* 59c33d2c6a804a8a1e2c16416ef7448e679b0b58 (2017-09-07) fails
* 3edc8e0cd901db1a5d12c384ddecd3f7f8ebeb3e 0.8.0 fails
* 150d2706f9b564e7961b0c30bd7b7e4dd6c37253 current master fails

**Comment by b-r-u** [comment]
It looks like this issue is connected with the move from the XFree86 API to XRandR in the mentioned commit 59c33d2c6a804a8a1e2c16416ef7448e679b0b58. Explicitly requesting an X11 backend highlights the issue here:
`$ WINIT_UNIX_BACKEND=x11 cargo run --example window`
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibraryOpenError(OpenError { kind: Symbol, detail: "XRRAllocateMonitor - /usr/lib/x86_64-linux-gnu/libXrandr.so.2: undefined symbol: XRRAllocateMonitor" })', /checkout/src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
The symbol `XRRAllocateMonitor` can not be found.
XRandR adds the concept of monitors in version 1.5 (See the [changelog](https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt?id=randrproto-1.5.0#n160)) but Debian 8.10 (jessie) still uses version 1.4 for libxrandr.

**Comment by b-r-u** [comment]
The code is actually careful to support older versions of XRandR:
https://github.com/tomaka/winit/blob/59c33d2c6a804a8a1e2c16416ef7448e679b0b58/src/platform/linux/x11/monitor.rs#L49-L51

But at this point the program already panicked by opening an interface to XRandr:
https://github.com/tomaka/winit/blob/59c33d2c6a804a8a1e2c16416ef7448e679b0b58/src/platform/linux/x11/xdisplay.rs#L31

**Comment by linde12** [comment]
Oh, great work. Sorry for thelate reply. I will be able to test this on monday.
