### ISSUE TITLE
winit 0.10.1/x11 render issue - top & right cut off

### ISSUE THREAD

**Issue by alexheretic** [tomaka/winit#398]
Today my projects are missing a small part of the top & right sections after updating to winit `0.10.1`. This appears to only affect **x11** (I tested in windows which was fine).

My projects are all affected using gfx/glutin, but this can also be reproduced by using [glium](https://github.com/glium/glium) `cargo update; cargo run --example image`

### winit 0.10.1 (cut off top & right)
![glium-winit-0 10 1](https://user-images.githubusercontent.com/2331607/35862288-0f9d83ec-0b43-11e8-9e73-2614cf6b2e64.png)

### winit =0.10.0 (expected)
![glium-winit-0 10 0](https://user-images.githubusercontent.com/2331607/35862294-1456ec2a-0b43-11e8-9fa0-2059f13c5d15.png)

* _Rendering is correct simply by adding `winit = "=0.10.0" to the Cargo.toml`_
* _Window inner size of 400x300 was used for the screenshots_
* _Testing on Arch Linux / Gnome_

**Comment by tomaka** [comment]
Probably an HiDPI issue.

**Comment by alexheretic** [comment]
I've narrowed down the regression to being introduced with 150d2706f9b564e7961b0c30bd7b7e4dd6c37253 (#386).

My hidpi_factor is `1` before & after, so I don't think that is an issue.

**Comment by alexheretic** [comment]
This issue is present all x11 DE/WMs on my setup. It's least pronounced in i3, but there is still a difference _(mostly the right cut off)_.

## Gnome
![gnome-winit](https://user-images.githubusercontent.com/2331607/35920002-804a1a4e-0c0e-11e8-99a9-d5e4a6863821.png)
## KDE Plasma
![kde-plasma-winit](https://user-images.githubusercontent.com/2331607/35920011-88fac440-0c0e-11e8-9d49-d960929a9eef.png)
## Xfce
![xfce-winit](https://user-images.githubusercontent.com/2331607/35920022-8ee57116-0c0e-11e8-916f-faa49fad1c49.png)
## Mate
![mate-winit](https://user-images.githubusercontent.com/2331607/35920032-95f6cd6a-0c0e-11e8-9dc1-f4cae6d64362.png)
## Budgie
![budgie-winit](https://user-images.githubusercontent.com/2331607/35920038-9bede078-0c0e-11e8-8bde-097f0070f5d8.png)
## i3
![i3-winit](https://user-images.githubusercontent.com/2331607/35920055-af249312-0c0e-11e8-8a56-6eb71f8932c4.png)
_Note: I sized i3 manually_

**Comment by alexheretic** [comment]
I've just tested this on separate hardware too, running Ubuntu 16.04
![screenshot from 2018-02-07 14-27-38](https://user-images.githubusercontent.com/2331607/35921706-557f10b2-0c13-11e8-8053-66fb018a493f.png)

I think this + @b-r-u's example shows this does indeed affect all x11 setups. We should probably revert  150d2706f9b564e7961b0c30bd7b7e4dd6c37253. Are you able to produce this @jwilm?

I wonder if we can automate a regression test for this - an image comparison under xvfb perhaps? It'd be nice to have a headless test for all backends ideally.

**Comment by jwilm** [comment]
@alexheretic The bug doesn't really show up on my machine because I only have 2 px borders, but there's no doubt it was introduced there. Rather than revert that commit, it would be reasonable to update that code to get the dimensions from the `Window` winit references and still return positioning data based on the most-parent window.

**Comment by jwilm** [comment]
@alexheretic does #402 resolve this for you?

**Comment by alexheretic** [comment]
@jwilm fair enough, yep I just checked it. Thanks for fixing this!

**Comment by b-r-u** [comment]
This commit works for me, too.

**Comment by alexheretic** [comment]
@tomaka We should merge #402 and release before closing this don't you think?

**Comment by tomaka** [comment]
Whoops! Merging the PR is now done, closing the issue is ok even when not released.
