### ISSUE TITLE
Most recent release breaks semver

### ISSUE THREAD

**Issue by Xaeroxe** [tomaka/winit#401]
I would strongly advise yanking 0.10.1 and re-releasing it as 0.11.  The addition of the `Caret` variant to the `VirtualKeyCode` enum breaks compatibility for code that is serializing and deserializing `VirtualKeyCode`s.

**Comment by Xaeroxe** [comment]
This is how this broke our build: https://travis-ci.org/amethyst/amethyst/jobs/338596041#L1012

**Comment by tomaka** [comment]
The problem with this issue is that whether adding an enum variant breaks semver/should break semver is a very open topic in the Rust community in general.

I haven't read enough literature to have a strong opinion on this.

**Comment by Xaeroxe** [comment]
This tool from rust-lang seems to indicate it is a semver break: https://github.com/rust-lang-nursery/rust-semverver

Specifically look under the **Functionality** heading.

**Comment by b-r-u** [comment]
The API evolution RFC also suggests that a new variant is a major change:
https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#major-change-adding-new-variants

**Comment by Xaeroxe** [comment]
Once [this RFC](https://github.com/rust-lang/rfcs/blob/master/text/2008-non-exhaustive.md) stabilizes you could add this trait to your enum to circumvent that, but for the time being it is not stable.

**Comment by Xaeroxe** [comment]
If you really want to get technical per the semver specification prior to 1.0 everything goes and nothing can be said to be truly semver breaking.  However this doesn't seem to be how the Rust community is behaving.

**Comment by tomaka** [comment]
Yanked 0.10.1 and opened #404
