### ISSUE TITLE
OS X SIGSEGV Running Examples

### ISSUE THREAD

**Issue by Hittherhod** [tomaka/winit#426]
I'm getting SIGSEGV when running the winit examples on Mac OS X. 
## OS X Version
`10.12.6`

## Rustc Version
```
rustc 1.26.0-nightly (5508b2714 2018-03-18)
```
## Error
```
cargo run --example grabbing                                                                   Mon Mar 19 20:39:58 2018
   Compiling winit v0.11.2 (file:///Users/rhodysn1/Development/winit)
    Finished dev [unoptimized + debuginfo] target(s) in 0.61 secs
     Running `target/debug/examples/grabbing`
fish: 'cargo run --example grabbing' terminated by signal SIGSEGV (Address boundary error)
```
This same error happens for each example.

**Comment by yvt** [comment]
I started seeing a similar issue after updating to the latest nightly. It ran perfectly with the stable compiler (`1.24.1 (d3ae9a9e0 2018-02-27)`). Probably it’s caused by a recent regression in `rustc`.

**Comment by francesca64** [comment]
@Hittherhod does everything work fine now with the latest master?
