### ISSUE TITLE
Use viewDidChangeBackingProperties on MacOS to detect when the DPI / monitor has changed

### ISSUE THREAD

**Issue by fschutt** [tomaka/winit#441]
I came across this interesting blog post: http://supermegaultragroovy.com/2012/10/24/coding-for-high-resolution-on-os-x-read-this/

It seems that macOS can call an application when the DPI or the monitor changes, given that `viewDidChangeBackingProperties` is implemented. In these cases, glium should emit a [HiDPIFactorChanged](https://docs.rs/winit/0.11.3/winit/enum.WindowEvent.html#variant.HiDPIFactorChanged) event, so that the application knows that it should update the DPI.

**Comment by sodiumjoe** [comment]
I'm implemented this in #443 using `windowDidChangeBackingProperties` according to https://developer.apple.com/documentation/appkit/nswindowdelegate/1419517-windowdidchangebackingproperties instead of `viewDidChangeBackingProperties`.
