### ISSUE TITLE
HoveredFile and HoveredFileCancelled events not implemented on Windows

### ISSUE THREAD

**Issue by francesca64** [tomaka/winit#448]

**Comment by dannyfritz** [comment]
Researched this a bit and found these 2 articles explaining how to do it:
https://www.codeproject.com/articles/840/how-to-implement-drag-and-drop-between-your-progra
https://msdn.microsoft.com/en-us/library/4w4z9dwh.aspx

Will have to switch from `WM_DROPFILES` to `OleDropTarget`.

**Comment by francesca64** [comment]
Oh, great! Do you want to implement it?

**Comment by dannyfritz** [comment]
I am looking at implementing it. I'm just secretly hoping it requires I do a PR to `winapi` so I can finally do something with Rust and creating FFI bindings.

**Comment by francesca64** [comment]
I think you're in luck; I'm 99% sure that it requires making a PR to `winapi`. That's a big part of why I never worked on this, since I'm too lazy for that.

**Comment by retep998** [comment]
[`IDropTarget`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679679)

**Comment by dannyfritz** [comment]
https://github.com/retep998/winapi-rs/pull/631 was merged. Implementation in `winit` is next. If anybody wants to take that up please do. If I start working on it I will post here.

**Comment by ArturKovacs** [comment]
Hi! I seem to have a working implementation. I needed to add one or two things to winapi-rs as well so first I'm going to create a PR for winapi-rs probably tomorrow.

**Comment by ArturKovacs** [comment]
retep998/winapi-rs#651

**Comment by francesca64** [comment]
Fixed via #662
