### ISSUE TITLE
4k HiDPI monitor detected as 2560x1440 on Windows 10

### ISSUE THREAD

**Issue by eterevsky** [tomaka/winit#469]
OS: Windows 10 Home, Version 1708, build 16299.371
winit version: 0.11.3
GPU: Nvidia GTX 1080, driver 385.54
Scaling factor: 150%

```rust
events_loop.get_primary_monitor()
```

produces `MonitorId` with name = "\\.\DISPLAY1", dimensions = (2560, 1440), position = (0, 0), hidpi_factor = 1

```rust
winit::WindowBuilder::new().with_fullscreen(Some(events_loop.get_primary_monitor()))
```

changes monitor resolution to 2560x1440 instead of using native 3840x2160.

**Comment by francesca64** [comment]
With #457, setting fullscreen doesn't change monitor resolution at all, so optimistically that's fixed there too.

**Comment by eterevsky** [comment]
On master only the first part of the issue can be reproduced, i.e. a 4k monitor is reported as having dimensions 2560x1440 and scale factor 1 instead of 1.5. However, creating a fullscreen window doesn't change the resolution, which is nice.

**Comment by francesca64** [comment]
That sounds like it's probably related to DPI awareness, which there's a seemingly abandoned PR for (#332). Getting that ready for merge is on my to-do list, so I'll let you know when that happens.

**Comment by kwonoj** [comment]
I'm interested in this issue as well, curious plans around #332 - allows some other contributor than the original author could possibly try to rebase to master and create new PR or honor and wait for original author or owner chimes in? @francesca64

**Comment by francesca64** [comment]
@kwonoj I've been planning on rebasing it myself. I've just been busy working on other improvements, so it's been pushed back a few times. I should be able to start working on it today though.

**Comment by francesca64** [comment]
This took much longer than I thought it would, but you'll see why when you see the PR: #548
