### ISSUE TITLE
'No backend is available' on NixOS

### ISSUE THREAD

**Issue by goertzenator** [tomaka/winit#493]
I am struggling to get winit running on NixOS.  I get the same error for conrod and glutin.  I don't know a lot about backends so I don't know where to start looking to resolve this.  Any help would be appreciated.

This machine is running KDE Plasma and I can run glxgears.

```
[goertzen@asusnixos:~/winit]$ cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/window`
thread 'main' panicked at 'No backend is available', src/platform/linux/mod.rs:364:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by francesca64** [comment]
Are you using Wayland?

**Comment by francesca64** [comment]
I've made a branch that should print diagnostic info when it fails: https://github.com/francesca64/winit/tree/x11-avail-debug

**Comment by goertzenator** [comment]
Just did a bit of drilling in `xdisplay.rs` on my own and found the error below.  Continuing to investigate.  NixOS can put things in strange places.

```
OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" }'
```

**Comment by goertzenator** [comment]
Hmmmmm...

```
[goertzen@asusnixos:~/winit]$ cat target/debug/build/x11-dl-d8a3342418266df5/out/config.rs 
pub mod config { pub mod libdir {
pub const xext: Option<&'static str> = None;
pub const gl: Option<&'static str> = None;
pub const xcursor: Option<&'static str> = None;
pub const xxf86vm: Option<&'static str> = None;
pub const xft: Option<&'static str> = None;
pub const xinerama: Option<&'static str> = None;
pub const xi: Option<&'static str> = None;
pub const x11: Option<&'static str> = None;
pub const xlib_xcb: Option<&'static str> = None;
pub const xmu: Option<&'static str> = None;
pub const xrandr: Option<&'static str> = None;
pub const xtst: Option<&'static str> = None;
pub const xrender: Option<&'static str> = None;
pub const xscrnsaver: Option<&'static str> = None;
pub const xt: Option<&'static str> = None;
}
}
```

**Comment by francesca64** [comment]
You could try reporting [upstream](https://github.com/Daggerbot/x11-rs/blob/master/x11-dl/build.rs). Worst case scenario, I can install NixOS in a VM and dig into this, but hopefully somebody knows more about this already.

**Comment by goertzenator** [comment]
Thanks, this is definitely between x11-rs, pkgconfig, and NixOS.  I need to study NixOS and pkg-config-rs a little more before pushing this intelligently upstream.  I suggest closing this issue.

**Comment by Ekleog** [comment]
(been invoked to give an idea about how to solve the issue from the NixOS side, didn't read all the details)

For NixOS, if this is due to x11-dl not finding the x11 libs, the solution will likely be either to not use dlopen (and link dynamically), which would likely be the preferred way, if possible at all.

The alternative solution would likely be to set a wrapper that defines LD_LIBRARY_PATH, something like:
```nix
{
  # ...
  postInstall = ''
    wrapProgram $out/bin/[mybinary] \
      --suffix LD_LIBRARY_PATH : ${pkgs.[the package that provides libx11.so]}/lib/libx11.so
  '';
}
```

**Comment by francesca64** [comment]
@goertzenator did you ever find a resolution on this?

**Comment by goertzenator** [comment]
No, but I've chosen to use something besides conrod/winit for the time being.  Thanks for checking in.

**Comment by goertzenator** [comment]
I've *almost* got this all worked out.  It turns out I need to run a `nix-shell` including `pkgconfig` and all the various xlibs.  I've found everything except `xlib_xcb`.  Could someone not on NixOS provide me with their `/usr/(share|lib)/pkgconfig/xlib_xcb.pc`?

**Comment by Pauan** [comment]
@goertzenator A few years late, but I was able to get it working by doing this:

```
nix-shell -p pkgconfig xorg.libX11 xorg.libXcursor xorg.libXrandr xorg.libXi
```

**Comment by wucke13** [comment]
Unfortunately, whay @Pauan mentioned does not work anymore, at least for me. I get the following error: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([NotSupported("lacking either libGL or libEGL so could not fallback to other"), NotSupported("both libGL and libEGL are not present")]))', egui_glium/src/backend.rs:112:84
```

Even if I put `LD_LIBRARY_PATH=/run/opengl-driver/lib:$LD_LIBRARY_PATH` in the shell.

**Comment by Pauan** [comment]
@wucke13 What if you use `nix-shell -p pkgconfig xorg.libX11 xorg.libXcursor xorg.libXrandr xorg.libXi libGL libGL.dev` ?

Note that you have to use `cargo run` or `cargo build` while inside of the `nix-shell`.

**Comment by wucke13** [comment]
> @wucke13 What if you use nix-shell -p pkgconfig xorg.libX11 xorg.libXcursor xorg.libXrandr xorg.libXi libGL libGL.dev ?

Then I get the same error. Of course I `cargo clean` before trying each new `nix-shell` command :)

**Comment by Bobbbay** [comment]
I'm getting the same error as @wucke13. Any update on this?

**Comment by TheSirC** [comment]
That is really weird @Bobbbay. Did you try to `cargo clean` first?  I use the script everyday without any problem.

**Comment by Bobbbay** [comment]
I just tried with a `cargo clean`, didn't help :(.

**Comment by rj00a** [comment]
@Bobbbay As a workaround you could try using [`steam-run`](https://nixos.wiki/wiki/Steam#steam-run) which worked for me.

**Comment by Bobbbay** [comment]
For me, now I get:

```
libEGL warning: MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([OsError("eglInitialize failed"), OsError("`glXQueryExtensionsString` found no glX extensions")]))', /home/bob/.cargo/registry/src/github.com-1ecc6299db9ec823/egui_glium-0.15.0/src/epi_backend.rs:45:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Under `steam-run cargo run` :).

**Comment by bitec0de** [comment]
@coderedart on [the egui discord](https://discord.gg/JFcEma9bJq) linked to a working nix flake here: https://github.com/emilk/egui/discussions/1587
