### ISSUE TITLE
Backend for SailfishOS

### ISSUE THREAD

**Issue by aprokurov** [tomaka/winit#499]
When i try to compile some piston examples or winit examples i get error that says 'No backeds available', but on Linux with Wayland it launching(SailfishOS using Wayland)

**Comment by aprokurov** [comment]
That's from wiki page:

> # Graphics

>The graphical display for Sailfish OS is handled by Qt and typically operates via a Wayland driver.


>3D-acceleration in Sailfish OS uses OpenGL ES 2.0 and EGL native platform interface APIs.


>Mer core provides the open source Mesa 3D Graphics Library containing OpenGL ES 2.0 and EGL libraries to link and build against, which can at image build time be replaced with device-specific OpenGL >ES 2.0/EGL implementations.


>In the core Mesa is built to use LLVMpipe for fast software rendering with no hardware specific drivers enabled.

**Comment by vberger** [comment]
Could you give us more information about your issue? Mostly:

- what are you trying to run (which examples)
- what fails exactly (is it compilation or running ? I'm sorry it does not appear clear from your message)
- a copy of the exact error message

Without these it'll be quite difficult to find out what is wrong.

**Comment by francesca64** [comment]
> what fails exactly (is it compilation or running ? I'm sorry it does not appear clear from your message)

"No backend available" looks like the panic we have [here](https://github.com/tomaka/winit/blob/fee874b5b76d457d3cca09dc1646f8e8f2c3c5f8/src/platform/linux/mod.rs#L364), which [as of recently](https://github.com/tomaka/winit/blob/master/src/platform/linux/mod.rs#L372) should be replaced with some diagnostic info. Are you running off of master, @aprokurov?

**Comment by aprokurov** [comment]
@vberger I'm running hello_world example from piston examples repo using dev-term, everything compiles fine, but not launching, RUST_BACKTRACE=1 don't give additional info

**Comment by aprokurov** [comment]
So, i cloned repository and compiled window example, getting [that](https://imgur.com/a/jMMQArT) error

**Comment by francesca64** [comment]
Ah, the Wayland backend just returns `Option<EventsLoop>`, so there's no info there.

**Comment by vberger** [comment]
Ah, yes, I need to improve that.

@aprokurov what version of the wayland libraries do you have on your system? winit requires >= 1.12.0

**Comment by vberger** [comment]
Also, we can likely get more information by setting `WAYLAND_RS_DEBUG=1`.

**Comment by aprokurov** [comment]
With `WAYLAND_RS_DEBUG=1` i get that:
```error
[wayland-client] Found library libwayland-client.so.0 cannot be used symbol wl_proxy_marshal_array_constructor_versionned is missing
```

**Comment by francesca64** [comment]
This appears to be related: tomaka/glutin#920

**Comment by vberger** [comment]
Yes, that means that the `libwayland-client.so` of your system is too old to be used by winit. We require at least version 1.12.0.
