### ISSUE TITLE
Crash when None is passed to set_fullscreen on Windows

### ISSUE THREAD

**Issue by ladlecrow** [tomaka/winit#501]
Glutin / Winit panics if one passes None to set_fullscreen(..) on a window 
that hasn't been fullscreened prior.

Noticed this while testing code on windows while using glutin:

```rust
// ...

let window = glutin::GlWindow::new(window_builder, context_builder,
&events_loop).unwrap();

window.set_fullscreen(None); // will panic on windows

// ...
```

An easy fix would be something like this:

https://github.com/ladlecrow/winit/blob/3dd07152f088545e6c1898f21449d663adfd7314/src/platform/windows/window.rs#L429-L431

I'm unsure if if this is the right approach though.

**Comment by francesca64** [comment]
Thanks for catching this! The fix looks fine as-is, though if you wanted to make a PR, I'd want to see 1) a CHANGELOG entry, and 2) a comment explaining when the condition is triggered.

It would also be good to double check with @edwin0cheng

**Comment by ladlecrow** [comment]
sure thing, i'll get to it shortly.

**Comment by ladlecrow** [comment]
Submitted a PR (#502).
