### ISSUE TITLE
Wakeup can panic if the window is closed

### ISSUE THREAD

**Issue by asajeffrey** [tomaka/winit#559]
If a window is closed, and the winit event loop is woken up, then a panic can happen https://github.com/tomaka/winit/blob/262490d07447d6539cb4e5d52acf5d4c8ad21c13/src/platform/linux/x11/mod.rs#L1059

The stack trace when this happened to Servo is at https://github.com/servo/servo/issues/21027

**Comment by francesca64** [comment]
> If a window is closed

Does this happen if the window is closed but the event loop is still running?

**Comment by asajeffrey** [comment]
Yes, I think it's a race condition where the window gets closed but winit isn't aware that it is, so xconn is still alive.

**Comment by francesca64** [comment]
I looked at the servo bug, and this has nothing to do with the wakeup/`XSendEvent`. `BadDrawable` is from trying to render to a window that's already been closed; it's just that X11 is async, so the error isn't caught until you try to wakeup.

**Comment by asajeffrey** [comment]
Indeed, the problem is the `expect` which triggers a panic we can't recover from, rather than returning an error value.

**Comment by francesca64** [comment]
That's not something I'm in a position to fix at present. If that `expect` weren't triggered, then another one would be instead. Why are you trying to render to a window that's been closed? What version of winit is being used in servo? If it's 0.12, then I suspect updating will resolve this on its own.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/pull/21087 updates winit.

**Comment by atouchet** [comment]
@asajeffrey is this still an issue after the winit 0.16.1 update?

**Comment by francesca64** [comment]
Since we haven't heard back on this in a while, and it's something I'm reasonably confident has been fixed in recent versions, I'm closing this. Feel free to reopen if it's still an issue!
