### ISSUE TITLE
CursorMoved and MouseInput events happening in title bar

### ISSUE THREAD

**Issue by Dooskington** [tomaka/winit#560]
On macOS High Sierra, it seems like I am getting window events that I shouldn't be, when clicking on the title bar / window decoration area.

Is this a bug or intentional? I think these window events should be restricted to happen only in the inner window. I even loaded up a C++ SDL project to check how they handle it, and it does ignore the equivalent events in the title bar.

**Comment by francesca64** [comment]
This looks like it happens because we're getting "raw" events from `NSApp` instead of responding to events through `NSView`, and since I created the necessary infrastructure in #518 this should indeed be easy.

**Comment by francesca64** [comment]
Here you go: #561
