### ISSUE TITLE
Transparent example segfaults on OS X

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#57]
Original: https://github.com/tomaka/glutin/issues/619

**Comment by mitchmindtree** [comment]
This no longer segfaults, but `panic!`s due to the `unimplemented!()` macro invocation [here](https://github.com/tomaka/winit/blob/master/src/platform/macos/mod.rs#L289). Maybe this issue title could be changed to "Transparency not yet implemented on OS X".

**Comment by frewsxcv** [comment]
I have this implemented in a branch. Will open a PR shortly.

**Comment by frewsxcv** [comment]
Blocked on https://github.com/servo/cocoa-rs/pull/144

**Comment by frewsxcv** [comment]
PR opened: https://github.com/tomaka/winit/pull/95
