### ISSUE TITLE
libxkbcommon.so is not present OOTB on most distros, causing wayland keyboard handling to silently fall back to raw scancodes only.

### ISSUE THREAD

**Issue by whentze** [tomaka/winit#597]
I realize this was my own fault, but after spending so many hours tracking down the root cause of this problem, I think it should at least be documented so others can avoid it.

- [This comment](https://github.com/tomaka/winit/blob/v0.13.0/src/platform/linux/wayland/keyboard.rs#L85) from winit's wayland keyboard handling code states that, on systems with a wayland compositor, libxkbcommon is most likely installed anyway. This is correct, however
- wayland-client-toolkit tries to [dlopen "libxkbcommon.so"](https://github.com/Smithay/client-toolkit/blob/master/src/keyboard/ffi.rs#L257) when initializing the keyboard, and
- On many distros, you will usually only have "libxkbcommon0" installed, so there will only be "libxkbcommon.so.0", not an unversioned .so file. To get "libxkbcommon.so", which would be a symlink to "libxkbcommon.so.0", you usually need the libxkbcommon-dev or -devel package, which is *not* usually installed.
This is the case on [Debian](https://packages.debian.org/da/jessie/amd64/libxkbcommon0/filelist), [Ubuntu](https://packages.ubuntu.com/bionic/amd64/libxkbcommon0/filelist), [Fedora](https://koji.fedoraproject.org/koji/rpminfo?rpmID=12673378#filelist), [CentOS](https://centos.pkgs.org/7/centos-x86_64/libxkbcommon-0.7.1-1.el7.x86_64.rpm.html) and [OpenBSD](https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/x11/xkbcommon/pkg/PLIST?rev=1.2&content-type=text/plain).
- On those plattforms, winit just silently falls back to `raw_keyboard_impl()`, which is not very useful.

There are several options for making this better:
-Change the client toolkit so it looks for "libxkbcommon.so.0" instead. This has the benefit of avoiding breakage in case an incompatible "libxkbcommon.so.1" is released.
-Explicitly document that the unversioned "libxkbcommon.so" is a dependency, and hint users towards installing the -dev package.
-Emit a warning (log?) message when falling back to raw input, also possibly hinting towards the -dev package.

**Comment by vberger** [comment]
> -Change the client toolkit so it looks for "libxkbcommon.so.0" instead. This has the benefit of avoiding breakage in case an incompatible "libxkbcommon.so.1" is released.

This is absolutely the right thing to do and what I'll do. I've already been bitten once by this on `wayland-sys` and apparently not learned from it... :disappointed:

**Comment by vberger** [comment]
Okay, if released `smithay-client-toolkit` version `0.2.5` that first tries to load `libxkbcommon.so.0` and fallbacks on `libxkbcommon.so`. Can you confirm `cargo update` solves this issue?

**Comment by whentze** [comment]
Yep, works just fine. Than you!
