### ISSUE TITLE
Possible unsoundness on windows

### ISSUE THREAD

**Issue by andrewhickman** [tomaka/winit#599]
This is just something that stuck out as odd to me while browsing the source, so I could be completely wrong here, but the windows backend seems to have some thread-safety issues. `Window` is marked with `unsafe impl Send + Sync` but contains some `Cell` and `RefCell`. Looking at, for example, [`set_resizable`](https://github.com/tomaka/winit/blob/c1ef1acfc0a6d372519c3cf1a1c1e0696373fa61/src/platform/windows/window.rs#L285) (which is exposed in the public API) these seem to get used without additional synchronisation.

**Comment by francesca64** [comment]
Hm, this looks problematic... worse still, I think I was the one who let this pass code review! Then because of the magic of technical debt, people who added more members over time used `Cell` too.

Do you want to fix this, or should I?

**Comment by andrewhickman** [comment]
I'm happy to fix this :)

**Comment by francesca64** [comment]
Fixed via #601
