### ISSUE TITLE
Use new objc class macro

### ISSUE THREAD

**Issue by grovesNL** [tomaka/winit#604]
[objc added a `class` macro](https://github.com/SSheldon/rust-objc/issues/65) which caches access to the class. So basically we can simply replace all `Class::get("x").unwrap()` with `class!(x)`. The `unwrap` isn't needed anymore because the macro will panic if it fails. Note also that this macro should eventually (through procedural macros) be able to link directly to the class.

I'd be happy to send a PR which performs this replacement, but cases like https://github.com/tomaka/winit/blob/master/src/platform/ios/mod.rs#L173 need to be clarified (do these ever actually fail?).

**Comment by francesca64** [comment]
Nah, those never fail, at least in a sane world. I'd be happy to see a PR for this, so thanks in advance.
