### ISSUE TITLE
winit crashes with SIGILL on latest nightly due to x11-rs

### ISSUE THREAD

**Issue by GabrielMajeri** [tomaka/winit#620]
This is an issue with the [x11-rs](https://github.com/erlepereira/x11-rs) crate ([again](https://github.com/tomaka/winit/issues/376)) triggering undefined behavior, see erlepereira/x11-rs#90.

For now, using `winit` on the nightly channel leads to crashing.

**Comment by OvermindDL1** [comment]
Running the latest amethyst project example gave me this same issue on nightly in --release mode only, debug works and stable works for both debug and release. No amount of cargo update and so forth did anything to help the issue. I can probably still reliably replicate the issue if required, though considering it's nightly...
