### ISSUE TITLE
macos: modified key issues

### ISSUE THREAD

**Issue by sodiumjoe** [tomaka/winit#625]
Not totally sure these are all related, but:

https://github.com/jwilm/alacritty/issues/1336
https://github.com/jwilm/alacritty/issues/1358
https://github.com/jwilm/alacritty/issues/1428
https://github.com/tomaka/winit/issues/623

I suspect these all started with https://github.com/tomaka/winit/pull/518

@francesca64 has given some direction [here](https://github.com/jwilm/alacritty/issues/1428#issuecomment-404956134)

**Comment by sodiumjoe** [comment]
just confirmed these all started with #518 by `git bisect`ing.

**Comment by sodiumjoe** [comment]
One interesting thing to note is for https://github.com/jwilm/alacritty/issues/1336, this might be working as intended? When I run the `multiwindow` example, <CMD-`> correctly cycles me through the open windows. I say "correctly," because this is normal macos app behavior.

Apparently `<CMD-.>` is [used for cancel](http://osxdaily.com/2014/04/05/cancel-button-keyboard-shortcut-mac-osx/) (though I can't find official documentation for that anywhere), and `<C-TAB>` is [Move to the next control when a text field is selected	](https://support.apple.com/en-us/HT204434).

Since `<C-TAB>` and `<CMD-.>` is sort of application dependent behavior, I guess winit should just pass these key events through to the consuming application.

But for <CMD-`>, I'm not sure, since this is standard app/window behavior. Should winit just handle this? Should it be default behavior with an option to opt out from an application?

**Comment by francesca64** [comment]
I'm generally in favor of winit conforming to the conventions of the platform, which would entail letting the OS handle ``<CMD-`>``. The only reason winit could previously override it was because our keyboard handling was overtly non-standard.

**Comment by francesca64** [comment]
Yes. Even if I weren't against it conceptually, [the potential fix](https://github.com/francesca64/winit/tree/macos-grave) is unreasonably convoluted.

**Comment by sodiumjoe** [comment]
So I found [this](https://github.com/adobe/chromium/blob/master/content/browser/renderer_host/render_widget_host_view_mac.mm#L1530), which in my testing appears to fix the `<C-Tab>` issue:

before:
```
WindowEvent { window_id: WindowId(Id(140332214940576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140332214940576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 48, state: Released, virtual_keycode: Some(Tab), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140332214940576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

after:
```
WindowEvent { window_id: WindowId(Id(140623425336880)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140623425336880)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 48, state: Pressed, virtual_keycode: Some(Tab), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140623425336880)), event: ReceivedCharacter('\t') }
WindowEvent { window_id: WindowId(Id(140623425336880)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 48, state: Released, virtual_keycode: Some(Tab), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140623425336880)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

But it doesn't fix the `<Cmd-.>` issue.  But I did find [this](https://github.com/glfw/glfw/blob/master/src/cocoa_window.m#L881), which appears to be addressing the same issue. I haven't quite figured out how to port this over yet, but I'm working on it.

**Comment by sodiumjoe** [comment]
https://github.com/tomaka/winit/pull/629

**Comment by sodiumjoe** [comment]
that branch fixes `<C-Tab>` and `<Cmd-{key}>` release, but not `<Cmd-.>`.

**Comment by sodiumjoe** [comment]
Interestingly, with `<Cmd-.>`, it's the keydown that's suppressed and the keyup that fires. Unfortunately, the same trick doesn't seem to work:

```
                if let Some(key_window) = maybe_key_window() {
                    if event_mods(ns_event).logo && ns_event.keyCode() == 47 {
                        println!("keycode: {}", ns_event.keyCode());
                        msg_send![*key_window.window, sendEvent:ns_event];
                    }
                }
```

the `println` fires, but the key event does not.

**Comment by sodiumjoe** [comment]
Ok, added special handling for `<Cmd-.>` that appears to work.
