### ISSUE TITLE
Extract PhysicalSize, LogicalSize & related data structures to a new crate?

### ISSUE THREAD

**Issue by anderejd** [tomaka/winit#631]
How about a new crate on crates.io, let's call it `dpi`?

**Comment by francesca64** [comment]
Why?

**Comment by anderejd** [comment]
Instead of glutin reexporting them was the idea. ¯\_(ツ)_/¯ Really minor annoyance when reading the docs, feel free to close.

**Comment by francesca64** [comment]
Well, glutin would still be full of re-exports... it would make more sense to have a notice in glutin's top-level docs indicating as much.

**Comment by anderejd** [comment]
Sounds very reasonable. Closing.
