### ISSUE TITLE
resizability & min/max dimensions

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#65]
Original: https://github.com/tomaka/glutin/issues/681

**Comment by LPGhatguy** [comment]
It appears that this might be two separate issues:
1. We need a `resizable` flag for creating windows
2. `with_min_dimensions` and `with_max_dimensions` include the window border on (at least) Windows, which is likely a bug.

**Comment by francesca64** [comment]
1. Closing in favor of #540
2. Fixed by #444 (it's actually still an issue on macOS, but a fix for that is shoved into my upcoming DPI PR)
