### ISSUE TITLE
ModifiersState not working on Wayland

### ISSUE THREAD

**Issue by NyxCode** [tomaka/winit#653]
During a `MouseWheel` event, all fields of the `ModifiersState` struct are false, even when the according key is pressed.

`Linux 4.14.68-1`, `Gnome 3.28.3` on `Wayland`

**Comment by NyxCode** [comment]
*Edit:* This exclusively occurs when getting the `ModifiersState` from a `MouseWheel` event - the `ModifiersState` from a `KeyboadInput` event works fine.

**Comment by NyxCode** [comment]
How to reproduce:
```
git clone https://github.com/NyxCode/winit-bug-report
cd winit-bug-report
cargo run
```
Then, scroll within the white window and watch `stdout`

**Comment by vberger** [comment]
Indeed, all the access of `ModifiersState` in the pointer-handling logic are currently dummies, like this:

https://github.com/tomaka/winit/blob/5a0bc016e77c3d69e0539899a3dc3f105302d1a1/src/platform/linux/wayland/pointer.rs#L46-L47

**Comment by NyxCode** [comment]
Oh, so no surprises here..
I have absolutely 0 knowledge of Wayland and winit, so I won't be able to help with this, but doesn't this possible break a lot of applications on wayland? I guess things like that should be at least documented :slightly_smiling_face:

**Comment by trimental** [comment]
For the record, I have a PR to fix this once https://github.com/Smithay/client-toolkit/commit/8fd8f5265f8d1f2e36d1f448b6ef1940b7d07aac is released
