### ISSUE TITLE
Title doesn't get displayed on Wayland

### ISSUE THREAD

**Issue by Cherser-s** [tomaka/winit#657]
Despite specifying title in `WindowBuilder`, title doesn't getting displayed regardless of decorations being set. (Decorations only affect the internal application bar (which is displayed on Wayland only) instead of borders and title bar (as it is done on X11 backend))

**Comment by vberger** [comment]
This is a work in progress in SCTK: https://github.com/Smithay/client-toolkit/pull/35

**Comment by vberger** [comment]
Actually under wayland, some compositors add their own decorations (like KDE or sway) and some don't (like Gnome or Weston).

The status quo is that by default the clients must assume the compositor doesn't draw anything, and there is a protocol extension to negotiate which side should decorate for compositors that support server-side decorations. The support for this extension will be added to winit by #655.
