### ISSUE TITLE
Event::Moved isn't working

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#67]
Original: https://github.com/tomaka/glutin/issues/724

**Comment by francesca64** [comment]
`WindowEvent::Moved` was implemented for X11 back in 22bc119cd76454846266786ed5ca150f872a2a43. It's still not implemented for OS X; the only other backend that implements this is Windows.

**Comment by vberger** [comment]
Bringing back my note from the original issue : this event simply can't be implemented on wayland, by design of the protocol.
