### ISSUE TITLE
window.set_maximized does nothing on Windows 10

### ISSUE THREAD

**Issue by Bzomak** [tomaka/winit#670]
Using the fullscreen example, toggling decorations and fullscreen works, but there is no noticable effect with the set_maximized method.

**Comment by Bzomak** [comment]
Okay, I've done some playing around, and it does trigger sometimes, but there seems to be some sort of interaction between the fullscreen state that is getting muddled. Time to dive further into the code...

**Comment by francesca64** [comment]
Fixed via #672
