### ISSUE TITLE
Events are broken when opening multiple windows

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#68]
Original: https://github.com/tomaka/glutin/issues/727

**Comment by francesca64** [comment]
I've been testing this, and all of the events have the correct window IDs.

The odd exception is a single `CursorMoved` event received immediately after a `Focused` or `CursorEntered` event. It has an ID that doesn't match any existing window, and a `DeviceId` of 3, which is notable in that it's the virtual core keyboard ID (in other words, it's a pretty badly malformed event!). However, that's not directly related to this issue, and is addressed in #372.

**Comment by knappador** [comment]
Two-window application on X11 only sends events to one of my windows, oddly the creation order doesn't matter and one window is favored to receive after it is created, though both threads are still spinning the render loop and polling.

In #252 it looks like we don't intend to support multiple event loops?

I was going to implement a single loop and transmit to all windows, but this does raise a few issues:

* `WindowBuilder.build()` does not accept an `EventLoopProxy` or any other type to avoid creating multiple loops unless all windows are created in one thread and passed around, but even if so...
*  What is `WindowEvent` to one window is only seen as `DeviceEvent` to another and this relationship will be incorrectly stated for two windows using one loop?

Should this issue be closed?

**Comment by knappador** [comment]
@francesca64  should I expect that if I create my event loop and windows in one thread, send the windows to the caller threads, and have them wake the event loop via proxy, that the events for both windows will arrive to the single `EventLoop` with the correct type / window ID so that I can dispatch them across my application?
