### ISSUE TITLE
X11 stuck in drag'n'drop mode after dragging element above window

### ISSUE THREAD

**Issue by chrisduerr** [tomaka/winit#687]
When dragging a Firefox tab across a winit window, X11 will get stuck in drag'n'drop mode, but the dragged item gets lost. So it's not possible to just go back to Firefox and drop the tab again.

In i3, this makes it impossible to kill windows, change workspace, spawn windows, or do anything really. The only way to fix this problem is by killing Firefox.

This doesn't seem to be a Firefox issue, but is reproducible with other drag'n'drop things like files or text (Engrampa, Gedit have been tested).

Alacritty issue as reference: https://github.com/jwilm/alacritty/issues/1713

**Comment by francesca64** [comment]
Thanks for bringing this to my attention! X11 drag-and-drop was my first ever contribution to winit, so I'm glad to have an excuse to recheck my old work.

This fixed the problem for me when testing on Compiz: #688

**Comment by haarp** [comment]
Thanks for the timely fix!
