### ISSUE TITLE
smithay-client-toolkit fails 1.24.1 Linux builds

### ISSUE THREAD

**Issue by Osspial** [tomaka/winit#698]
The root cause seems to be from [`stb_truetype`](https://crates.io/crates/stb_truetype), which is depended on by [`smithay-client-toolkit`](https://crates.io/crates/smithay-client-toolkit) via [`andrew`](https://crates.io/crates/andrew) via [`rusttype`](https://crates.io/crates/rusttype).

**Comment by vberger** [comment]
Yes, some of our dependencies have made patch versions upgrades breaking rustc compatibility, however SCTK remains 1.24.1 compatible if these dependencies are forced to their older versions.

We are testing this in our travis script, like so: https://github.com/Smithay/client-toolkit/blob/6538cab77a6bde08d6784f8f1ebe818de38e0045/.travis.yml#L61-L68

This way, SCTK can remain its rustc compatibility without locking itself out of dependencies updates. I guess we could do the same thing for winit?

**Comment by Osspial** [comment]
We could. I'm not sure if that's really in the spirit of guaranteeing 1.24.1 compatibility, though - I read it as "you can download a copy of this library off crates.io and use it with 1.24.1 with no extra steps", which that doesn't really do.

**Comment by francesca64** [comment]
I agree with @Osspial that superficially making the CI pass isn't in the spirit of maintaining compatibility. I've created [an issue on `stb_truetype`](https://gitlab.redox-os.org/redox-os/stb_truetype-rs/issues/20) that will hopefully lead to an elegant resolution.

**Comment by vberger** [comment]
For the record before I forget (am on mobile right now), rusttype itself also broke the compatibility with their 0.7.2. 

Their only change from 0.7.1 is the update of their dependency ordered-float to 1.0, which does not compile on 1.24.1.

**Comment by francesca64** [comment]
At this point, I'm leaning towards just increasing the minimum required Rust version. It's been [6 months since we chose 1.24.1](https://github.com/tomaka/winit/issues/531). Now [Ubuntu 16.04 is up to 1.28.0](https://packages.ubuntu.com/xenial/rustc), and 1.28.0 is just as old as 1.24.1 was when we picked it. It's still unclear to me how important it is to be conservative with the required version, but either way, staying further back increases maintenance costs.

**Comment by Osspial** [comment]
I'm okay with doing that. I'm not aware of many reasons for enforcing a minimum version besides making sure code works on commonly-available distributions of Rust. If commonly-available distributions support a newer version, I don't see the point in sticking with a version that requires a significant amount of work on our end to support.

**Comment by vberger** [comment]
I also agree. I was on my side pondering the question of bumping the rust version in wayland-rs/sctk to improve the code with more recent rust features, but restrained myself to not break winit's guarantee.

**Comment by francesca64** [comment]
Should changing to 1.28.0 require a bump to 0.19.0? 0.18.0 already doesn't compile out of the box on 1.24.1, so it's sort of already an unlisted breaking change.

**Comment by vberger** [comment]
Well, in that case it's just a matter of updating the readme and the travis build I'd say.
