### ISSUE TITLE
Windows backend invokes undefined behavior upon panic

### ISSUE THREAD

**Issue by Osspial** [tomaka/winit#699]
Right now, panics in the Windows callback function invokes undefined behavior by unwinding into foreign code (see [here](https://doc.rust-lang.org/beta/nomicon/print.html#what-unsafe-rust-can-do)). This is going to become even more of a problem once the Event Loop 2.0 code gets merged and we're running *all* user code in the Windows callback. There should be a panic handler installed that catches the panic, kills the Windows event loop, then resumes panicking from the main event loop.

**Comment by francesca64** [comment]
Great idea! Would you like to implement this?
