### ISSUE TITLE
Discussion: Clipboard API

### ISSUE THREAD

**Issue by Osspial** [tomaka/winit#704]
As per #162 and #695, we've decided that Winit should support clipboard handling. This issue is intended to house discussion on the API.

Discussion points:
* In most cases, data that can be copied can also be dragged and dropped. To what extent should this be unified with the drag/drop API?
* Clipboards can contain quite a few types of content (e.g. text, images, sounds, files). How do we want to handle these clipboard data formats? When do we want to distinguish between formats, and when do we want to map multiple OS formats onto one exposed format?
  * Additionally, some OSes support data sub-types. How do we want to expose those?
    * Windows lets you copy HTML snippets for rich text, and Wayland supports full [MIME](https://www.freeformatter.com/mime-types-list.html) specification. 
* Oftentimes, clipboard data can include the same data in multiple formats (e.g. words in a plain-text vs a rich-text format). How do we handle this?
  * Similarly, how do we allow people to upload the same data in different formats to the clipboard?

**Comment by Osspial** [comment]
Also, how do we want to handle custom clipboard data formats? Supporting this would allow applications to use the system clipboard to store non-standard data, like mesh data in a 3D modeling app, which can be quite useful. It can also be used to embed application-specific metadata alongside standard formats - for example, Sublime Text embeds language information in a `sublime-text-extra` format.

**Comment by Osspial** [comment]
I'm closing this, since we've since decided against having a clipboard API.

**Comment by madsmtm** [comment]
We're discussing this again in https://github.com/rust-windowing/winit/pull/2156, for the people following this issue, feel free to drop by and give input!
