### ISSUE TITLE
Is there a reason winit uses `image = "0.20.1"` rather than `image = "~0.20.1"`?

### ISSUE THREAD

**Issue by icefoxen** [tomaka/winit#707]
The latter would allow `image` 0.20.2, etc to be used in case there's ever dependency updates.  `^0.20.1` would do the same, I think.

`ggez` habitually just specifies `image` 0.20 or whatever, so I'm already having nightmares of a user pulling a hypothetical `image` 0.20.2 and `ggez` mysteriously failing to build because of it.  Specifying ggez to use `image` 0.20.1 precisely is the simple solution, was just wondering if we could do better.

Thanks!

**Comment by vberger** [comment]
From the [cargo reference manual](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) specifying a dependency without any symbol prefix, as `"x.y.z"` is equivalent to `"^x.y.z"`.

As such running `cargo update` should be enough to grab a newer semver-commpatible version of image.

**Comment by icefoxen** [comment]
...shoot, I keep forgetting that.
