### ISSUE TITLE
Window freezes after moving window with hidden cursor

### ISSUE THREAD

**Issue by shivshank** [tomaka/winit#708]
I'm working on an FPS camera, using `grab_cursor` and `hide_cursor`.

I've noticed that moving the window freezes the whole event loop. The steps to reproduce in my app are:

- Start the app
- Alt-tab away / lose focus
- Click and drag on the title bar
- The window is now frozen and I have to either kill the process or ctrl-c in the console

If I remove all references to `grab_cursor` and `hide_cursor`, the window never freezes. (With *either* just `hide_cursor` or just `grab_cursor`, the window also still freezes, as it does when using both.)

My event loop is as follows:

```rust
let gl_window = GlWindow::new(window, context, &events_loop).unwrap();
gl_window.hide_cursor(true);
gl_window.grab_cursor(true)
    .unwrap();
// ... game loop:
let mut mouse_movement = (0.0, 0.0);
events_loop.poll_events(|event| {
    use glutin::{
        Event::*,
        WindowEvent::*,
        DeviceEvent::*,
        ElementState,
    };
    match event {
        WindowEvent { event: CloseRequested, .. } => running = false,
        WindowEvent { event: Focused(is_focused), .. } => {
            enable_camera = is_focused;
            window.hide_cursor(is_focused);
            window.grab_cursor(is_focused)
                .unwrap();
        }
        WindowEvent { event: KeyboardInput { input, .. }, .. } => {
            // ... handle input
        }
        DeviceEvent { event: MouseMotion { delta }, .. } => {
            mouse_movement = delta;
        }
        _ => {}
    }
});
```

**Comment by Osspial** [comment]
Which operating system are you running into this issue on?

**Comment by shivshank** [comment]
Windows 10. I also neglected to mention that I am using glutin 0.19 / winit 0.18.

I should probably try running it from the main branch directly, and double check it still happens... Also my rustc is 1.27 😬, I'll have to update that tomorrow, too.

**Comment by Osspial** [comment]
It looks like this has the same underlying cause as #689.
