### ISSUE TITLE
WindowEvent::MouseInput not triggered for LMB when holding keyboard key down on Windows 10

### ISSUE THREAD

**Issue by Wodann** [tomaka/winit#712]
When I press and hold down a keyboard key (e.g. W) and press the LMB mouse button, no `WindowEvent::MouseInput` is triggered. When I try to do the same thing for the RMB, a `WindowEvent::MouseInput` is triggered as expected.
Even more interestingly, if I:
1) Press and hold down a keyboard key (e.g. W) [no LMB event, RMB event is fine]
2) Press and hold down a second keyboard key (e.g. A) [no LMB event, RMB event is fine)
3) Release first key (i.e. W) [no LMB event, RMB event is fine]
4) Release second key (i.e. A) [LMB event is fine, as well as RMB event]

It seems as though the last keyboard key you press, prevents the LMB event from being registered as long as it held down. For example, this does work:
1) Press and hold down a keyboard key (e.g. W) [no LMB event, RMB event is fine]
2) Press and hold down a second keyboard key (e.g. A) [no LMB event, RMB event is fine)
3) Release second key (i.e. A) [LMB event is fine, as well as RMB event]

This behaviour translates to more than two keyboard keys too. It seems to be a very specific issue, but I can reproduce it time and time again.

I am experiencing this issue on Windows 10 using Rust v1.30.1 (stable-x86_64-pc-windows-msvc) and winit v0.18.

**Comment by francesca64** [comment]
Thanks for reporting!

I wasn't able to reproduce this when testing on Windows 10 with the snippet below.

```rust
extern crate winit;

fn main() {
    let mut events_loop = winit::EventsLoop::new();

    let _window = winit::WindowBuilder::new()
        .build(&events_loop)
        .unwrap();

    events_loop.run_forever(|event| {
        match event {
            winit::Event::WindowEvent {
                event: winit::WindowEvent::CloseRequested,
                ..
            } => return winit::ControlFlow::Break,
            winit::Event::WindowEvent {
                event: winit::WindowEvent::MouseInput { .. },
                ..
            } => println!("{:?}", event),
            _ => (),
        }
        winit::ControlFlow::Continue
    });
}
```

**Comment by Wodann** [comment]
Thank you @francesca64 for having a look. I just brought my code down to a minimal reproduction too of my code too. For me this reproduces it reliably. I am using the `poll_events` function as opposed to `run_forever`. It shouldn't make a difference, I think, but let me try that too:

```extern crate winit;

use winit::{Event, WindowEvent};

fn main() {
    let mut events_loop = winit::EventsLoop::new();

    let _window = winit::WindowBuilder::new()
        .build(&events_loop)
        .unwrap();

    let mut window_closed = false;
    while !window_closed {
        events_loop.poll_events(|ev| {
            match ev {
                Event::WindowEvent { event: WindowEvent::CloseRequested, .. } => window_closed = true,
                Event::WindowEvent { event: WindowEvent::KeyboardInput { input, .. }, .. } => {
                    //println!("Key {:?}: {:?}", input.virtual_keycode, input.state);
                },
                Event::WindowEvent { event: WindowEvent::MouseInput { button, state, .. }, .. } => {
                    println!("Button {:?}: {:?}", button, state);
                },
                _ => ()
            }
        });
    }
}```

**Comment by Wodann** [comment]
FYI, the bug persists for me with the `run_forever` loop.

**Comment by Wodann** [comment]
I was just wondering @francesca64 . Are you actually holding down a keyboard key when pressing the mouse button?

**Comment by Wodann** [comment]
Since it is working with you, and not for me, I figured there had to me something wrong other than in the winit library. As I am using a notebook for developing (with touchpad for mouse input), I figured I'd try using an external mouse to see if that'd work. Turns out that if I connect my external mouse, the problem does not occur. I guess it is a driver bug instead of a winit bug after all.

Sorry for questioning the winit lib 😅

**Comment by francesca64** [comment]
> Are you actually holding down a keyboard key when pressing the mouse button?

Yeah.

> Sorry for questioning the winit lib

No worries! It's important that we know about any difficulties users could experience.

If you're still interested in investigating this, you could let me know if you also have this problem with other software (or GLFW, SDL, etc.).
