### ISSUE TITLE
Is it possible to make an existing window fullscreen?

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#72]
Original: https://github.com/tomaka/glutin/issues/782

**Comment by francesca64** [comment]
This has been in the API as `Window::set_fullscreen` since #130, but it's only implemented on X11.

**Comment by francesca64** [comment]
Thanks to #457, this is now implemented on Windows.

**Comment by francesca64** [comment]
This was also implemented on Wayland back in #383.

**Comment by francesca64** [comment]
With #465, this is now implemented everywhere.
