### ISSUE TITLE
Inconsistent behavior between `with_dimensions` and `with_min_dimensions`

### ISSUE THREAD

**Issue by bitonic** [tomaka/winit#722]
On X11, `with_dimensions` takes a `LogicalSize` and converts it to a physical size with the high DPI factor -- so if I specify dimensions 800x600 with high DPI factor of 2 I'll end up with a window of physical size 1600x1200.

However, `with_min_dimensions`, while having a `LogicalSize` argument, seems to use it as physical size.

The easiest way to reproduce is to set the `with_dimensions` and `with_min_dimensions` as the same and then observe how the initial size is 4 times the size as the min size.

**Comment by bitonic** [comment]
Relatedly, it'd be good to have `dimensions` method that explicitly take a `PhysicalSize`

**Comment by francesca64** [comment]
Thanks for reporting! Does this branch fix the issue for you? https://github.com/francesca64/winit/tree/x11-with-physical

> Relatedly, it'd be good to have `dimensions` method that explicitly take a `PhysicalSize`

That would be trickier, as discussed here: https://github.com/tomaka/winit/issues/591#issuecomment-403113701

**Comment by bitonic** [comment]
@francesca64 that works, thank you so much!

**Comment by bitonic** [comment]
actually wait, i thought you had merged that branch! @francesca64 do you mind if i keep this open until that happens?

**Comment by francesca64** [comment]
Keeping it open is fine! It makes things cleaner if issues are only closed by the PRs that fix them.
