### ISSUE TITLE
[Mac] Can't drag and drop files when transparency is active

### ISSUE THREAD

**Issue by CryZe** [tomaka/winit#726]
When creating the window with `.with_transparency(true)` drag and drop does not work anymore on Mac.

**Comment by francesca64** [comment]
Why did you close this?

**Comment by CryZe** [comment]
Because this was a misdiagnosis. My VM was just lagging out so hard that it didn't accept the file. Although someone was able to reproduce it with a debug build on their actual Mac system. So drag and drop (and other inputs) lagging out may be an actual issue.
