### ISSUE TITLE
wayland: screen scale factor bugs

### ISSUE THREAD

**Issue by yorickvP** [tomaka/winit#736]
Sometimes when I set the scale factor to 2, and then back to 1, [alacritty does this](https://pub.yori.cc/um.png)

After a bit of debugging I produced the following log: https://pub.yori.cc/glutin.log

**Comment by vberger** [comment]
cc #724

**Comment by yorickvP** [comment]
The issue changed now (alacritty only updates when I mouse over it). This might be an alacritty bug.
