### ISSUE TITLE
BadDrawable with Vulkan/XLib window on Linux

### ISSUE THREAD

**Issue by kvark** [tomaka/winit#748]
Getting this when running any of the Ash or gfx-hal examples:
```
[winit X11 error] XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4
}
```
Apparently happens on `poll_events` without the user code doing anything, so may be inside `winit`.

Linux: 4.19.8-104.current #1 SMP PREEMPT Wed Dec 12 01:23:21 UTC 2018 x86_64 GNU/Linux

**Comment by kvark** [comment]
@Osspial note that it's super annoying, since it prevents me from running anything with Vulkan at the moment. Let me know if you have ideas, or if you don't have capacity to investigate.

**Comment by Osspial** [comment]
@kvark I've got a Linux machine, but I don't know if it supports Vulkan and I know basically nothing about how the X11 backend works. If Vulkan *does* work I'll see if I can reproduce this, but I'm afraid I don't have the expertise to do much else.

**Comment by kvark** [comment]
@Osspial does't sound like you'd be the best person to look into this problem, unless you do want to get more understanding of X11 and Vulkan. Should I reach out to other contributors? Or should I drop the hope for help and try to figure this out myself?

**Comment by Osspial** [comment]
@kvark It doesn't look like my Linux machine supports Vulkan, so I can't look into this. @francesca64 expressed interest in looking into this, so you should talk to her.

As far as other information that would be useful: if you run a Vulkan application that uses SDL to create windows, do you get a similar error? If you do, it's probably not an issue on our end.

**Comment by kvark** [comment]
Looks like even `vkcube` isn't showing anything, so it's not `winit`, phew!
Sorry about the trouble. I didn't realize my system is so dysfunctional at this point.

**Comment by yorickdewid** [comment]
Its likely Vulkan does not load the driver for the correct card. Try

```sh
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json vkcube
```

**Comment by Uniformbuffer3** [comment]
I have recently opened an issue on mesa about the problem and a developer have merged a patch that should fix the problem: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4688
