### ISSUE TITLE
Feature Request: Recolorable Title Bar on Wayland

### ISSUE THREAD

**Issue by JMurph2015** [tomaka/winit#765]
So I understand the whole issue with the non-native decorations under Wayland (decoration is done client side etc.).  However, it would go a long way to easing the situation if applications like Alacritty could support changing the color of the title bar, which has to start here.  How feasible does this sound?

**Comment by vberger** [comment]
For the record, SCTK already supports this, using the [`WIndow::set_theme`](https://docs.rs/smithay-client-toolkit/0.4.4/smithay_client_toolkit/window/struct.Window.html#method.set_theme) method, so this would not require any upstream changes.

I don't have time to implement this directly, but I can mentor anyone willing to work on this.
