### ISSUE TITLE
Deleted issue + PR

### ISSUE THREAD

**Issue by chrisduerr** [tomaka/winit#771]
This issue is unrelated to code, but it looks to me like a winit issue and PR was deleted and I'm unsure where this feature would be tracked now.

I'm specifically talking about the PR https://github.com/tomaka/winit/pull/755. Github still is able to properly show some metadata like name when hovering over that PR and it also shows that it's supposed to resolve #752, however neither the issue nor the PR seem to exist anymore.

While the management of issue tracker and PRs of winit are none of my business, this makes tracking of features across projects a bit difficult. Was this issue deleted as a duplicate of #753? And did the PR not sufficiently resolve this problem?

If this was some kind of mistake, I can open a new issue. But I wanted to make sure that this was not done intentionally first. Having both an issue and a PR just pop out of existence seems quite odd to me.

**Edit:** Looks like deleted issues are explicitly marked as such. So it must be something else? Was this intentional?

**Comment by francesca64** [comment]
This definitely wasn't intentional on my end. I'm not even aware of it being possible to delete issues/PRs (and it's not something I'd want to do anyway). I have no idea what could be happening here, but I'm sorry for any concern this has caused you.

**Comment by francesca64** [comment]
Now that I'm not on mobile, I can see the hovercard, and I'm even more surprised given what PR that was. That PR was on schedule to be merged, so this is a bummer.

The user who made the PR+issue also 404s, so I assume this is related to that: https://github.com/Toqozz

**Comment by chrisduerr** [comment]
Usually a user would change to the `Ghost` user when it's just deleted right?

This is just a complete guess, but maybe this is related to GDPR and that user specifically requested that all data associated to his account should be deleted? Maybe that would do it?

Might be possible to contact Github here, but there has been someone who tested that PR, maybe he still has the code at least.

**Comment by francesca64** [comment]
> Usually a user would change to the Ghost user when it's just deleted right?

Yup.

> maybe this is related to GDPR and that user specifically requested that all data associated to his account should be deleted?

That sounds plausible, but it's still weird. From the email notifications I have, they seemed enthusiastic about the PR just 2 days ago.

> there has been someone who tested that PR, maybe he still has the code at least.

I also have a checkout, but it's from before any of the revisions. The commits are still up though; AFAIK this is the last commit: 2d3d60c4665b8d3b8961304a93b00ac252032579

However, I'm not sure how respectful it would be to use their code, depending on what the actual circumstances are.

**Comment by chrisduerr** [comment]
> However, I'm not sure how respectful it would be to use their code, depending on what the actual circumstances are.

I'm not going to make any comment on how socially acceptable this is, however I think it should be fine from a legal point of view. However while it should be 'legal' to include the previously under GPL published code, it would obviously be impossible to change the license of winit or something else that requires copyright over the code (but that's near impossible anyways and the same for deleted users).

**Comment by Toqozz** [comment]
Should be fixed now -- is the PR visible again?

**Comment by chrisduerr** [comment]
Everything seems to be good again, thanks for the update!

Just out of curiosity, what did your account get flagged for? It seems odd to me that GitHub would just straight-up delete an issue and a PR like that.

**Comment by Toqozz** [comment]
There was no reason given, just “your account has been flagged”.

I have no idea what it could have been.
