### ISSUE TITLE
Allow getting monitor DPI scaling before creating a window

### ISSUE THREAD

**Issue by 5paceToast** [tomaka/winit#785]
It sometimes makes sense to define a window size in terms of a logical number, rather than raw pixels.
An example of this is a terminal emulator, that defines its window size as rows/columns.
In that example, the physical size (size of glyph * columns etc) is determined by the current monitor's DPI.
As such, please add the ability to query DPI information before a window is created.

The upstream issue on my mind is jwilm/alacritty#204, but I can see this applying to other use-cases (for example, tile-based games where you could define the window size based on how many tiles one wishes to see at a time, but that wish to scale their tiles based on DPI).

(direct copy-paste in place of move, as requested by @ZeGentzy over at https://github.com/tomaka/glutin/issues/1096 )

**Comment by vberger** [comment]
Well, it is already possible. From an `EventsLoop::get_available_monitors()` you can iterate over the monitors, and from each of them you can get its dpi factor using `MonitorId::get_hidpi_factor()`.

Now, you need some heuristic to decide what value to use if all the monitors don't have the same dpi factor, but winit cannot really help with that. There is no sensible way to know beforehand which monitor the window will be created on.

**Comment by 5paceToast** [comment]
@jwilm can you please elaborate on the specific issues you were having? (your [post](https://github.com/jwilm/alacritty/issues/204#issuecomment-271115472) suggests that you couldn't get the DPI at all)
