### ISSUE TITLE
Dropping Window doesn't close it (X11)

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#79]
Original: https://github.com/tomaka/glutin/issues/805

**Comment by mitchmindtree** [comment]
The window also doesn't close when pressing the **X** button either, even though the `Closed` event does get emitted. 

This is particularly evident in the multiwindow.rs example as you can press the **X** button on the same window 3 times to exit the loop.

I guess most folks haven't run across this in practise as

1. most applications have one window and
2. most applications probably manually break from the main loop when `Closed` is received, in turn exiting the program annd leaving the window for the OS to clean up.

This is my experience on the latest Gnome at least.
