### ISSUE TITLE
Add support for min/max dimensions on OSX

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#80]
Original: https://github.com/tomaka/glutin/issues/812

**Comment by frewsxcv** [comment]
I have a branch with this implemented. Will open a PR soon.

**Comment by frewsxcv** [comment]
Depends on https://github.com/servo/cocoa-rs/pull/142.

**Comment by frewsxcv** [comment]
PR opened: https://github.com/tomaka/winit/pull/89.
