### ISSUE TITLE
[macOS] command key event left and right reverse

### ISSUE THREAD

**Issue by TakWolf** [tomaka/winit#808]
Left command => RWin

KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } }

----------------

Right command => LWin

KeyboardInput { scancode: 54, state: Pressed, virtual_keycode: Some(LWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } }

**Comment by TakWolf** [comment]
winit version: 0.19.0

**Comment by Osspial** [comment]
Looks like the key-codes are just swapped around in the [key-code mapping function](https://github.com/tomaka/winit/blob/master/src/platform/macos/events_loop.rs#L663-L664). [The official key-code list](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h#L273) doesn't actually list a key-code for right command, so it seems like it would be a pretty easy mistake to make.

This should be a fairly easy problem to fix, so a PR would be welcome.
