### ISSUE TITLE
Fractional dpi factor support for wayland

### ISSUE THREAD

**Issue by vberger** [tomaka/winit#809]
Fraction dpi factor support can actually be achieved on wayland by combining two protocol extensions (assuming the server supports them):

- xdg_output provides additional metadata on the monitors, including their logical size, making it possible to compute a fractional dpi factor from it (and for the compositor to advertise a fractional dpi factor using it). 
- wp_viewporter allows a client to arbitrarily crop and resize their buffers. By choosing the appropriate scale factor, it can thus ensure that the size of the buffer in pixels exactly matches the size of the window as it'll be displayed, in which case no resizing will occur.

This depends on the integration of these two protocols in SCTK : https://github.com/Smithay/client-toolkit/issues/65 and https://github.com/Smithay/client-toolkit/issues/66

Help on that is welcome!

**Comment by vberger** [comment]
So, I've been explained that this would be an horrible hack and is not at all how these protocols are intended to be used.

**Comment by dhardy** [comment]
Perhaps not via this method, but given that both KDE and Gnome (experimental) now have some type of support for fractional scaling on Wayland, this should still be supported somehow?

**Comment by kchibisov** [comment]
This can't be done, since there's no such thing as a fractional scaling on Wayland on client side, it's done by compositor by rendering in e.g. 2x and then scaling down to whatever you've provided, since there's no fractional scaling factor on a protocol level.

**Comment by dhardy** [comment]
That explains why font rendering in KDE/Wayland is so ugly. Gross. Fine, lets forget Wayland.
