### ISSUE TITLE
Live chat for support?

### ISSUE THREAD

**Issue by ZeGentzy** [tomaka/winit#816]
So, a glutin user pointed this out to me (@slmjkdbtl), that winit has no channel for real time chatting, which is something that, I feel, is better suited for providing support to users than filing an issue.

I could setup a freenode-matrix-gitter triplet like I did for [glutin](https://github.com/tomaka/glutin#contact-us) if you folks are interested. Users can hop onto whichever of the three they are more conformable with and their traffic gets relayed to the other two channels.

The channels would likely be #glutin-winit for freenode (since I already own #glutin-*) #Winit:matrix.org for matrix and ZeGentzy/winit for Gitter.

Alternatively (and this is what I'd prefer), we could share the existing channels for glutin between both projects as the channels will probably be really low traffic and users have a hard time as-it-is distinguishing glutin issues from winit ones.

**Comment by vberger** [comment]
I'd not be against any of these solutions.

If glutin's chatroom is indeed low-traffic, it may make sens to unite them, given there is indeed a large set of interactions between the two projects.

**Comment by Osspial** [comment]
Closing this now that #818 has been merged.
