### ISSUE TITLE
Plans for adding platform-specific standard keyboard shortcuts?

### ISSUE THREAD

**Issue by slmjkdbtl** [tomaka/winit#820]
Things like `<command+q>` to quit on macOS, which is implemented in some other windowing libraries (sdl even have `<command+ctrl+f>` to toggle fullscreen by default). Wondering if winit is planning to implement these or let users handle?

**Comment by Osspial** [comment]
Hi, and thanks for the question!

There are no plans to implement this on our end. Winit's goal is to provide the minimal API necessary for users to create windows and desktop applications in a consistent way across platforms, and defining platform-specific keyboard shortcuts falls outside that scope. There's definitely room for another crate to expose definitions for platform-native keyboard shortcuts, though!

**Comment by slmjkdbtl** [comment]
I see, thanks!

**Comment by Osspial** [comment]
So... I'm going to backtrack a bit here. Looks like there's some ongoing discussion about this in #41 which has broad support for implementing this in some form.
