### ISSUE TITLE
Windows icon loading broken since glutin 0.20

### ISSUE THREAD

**Issue by chrisduerr** [tomaka/winit#828]
I've just bisected the downstream issue https://github.com/jwilm/alacritty/issues/2260 in Alacritty and noticed that an update to glutin 0.20 has broken Icon support on Windows.

This is specifically about the `with_window_icon` call. I haven't been able to test this on X11 myself yet.

I've bisected winit and it turns out https://github.com/tomaka/winit/commit/7be1d16263be372f33258eb48efbab933f80afe4 is the culprit.

**Comment by Osspial** [comment]
Thanks for the report! I'll look into what's causing this.
