### ISSUE TITLE
Add repr(u8) for VirtualKeyCode

### ISSUE THREAD

**Issue by Emilgardis** [tomaka/winit#87]
Enabling repr(u8) would mean that an array could be used for handling keys via i.e ecs instead of a hashmap. See amethyst/amethyst#114

**Comment by torkleyy** [comment]
@Emilgardis are you sure `u8` is enough?

**Comment by Emilgardis** [comment]
Yes, `VirtualKeyCode`s variants spans [L143-321](https://github.com/tomaka/winit/blob/4c6e4e827a017defb47346c4a7838f8c7bbc3d86/src/events.rs#L143-L321), this means that we have less than 255 lines, i.e there are less than 255 variants on `VirtualKeyCode`

**Comment by torkleyy** [comment]
@Emilgardis yes, but what if somebody wants to add more keys?

**Comment by vberger** [comment]
Adding more keys to an enum is a breaking change anyway, so I guess the repr could be changed to u16 at the same time if needed?

**Comment by Emilgardis** [comment]
Exactly my thoughts
