### ISSUE TITLE
allow creation of child window

### ISSUE THREAD

**Issue by k-brac** [tomaka/winit#93]
It would be nice if we could create child window.
I can see 2 features : 
- use of the safe rust API (mostly already existing)
- unsafe API for FFI

-> I am experimenting in developing a plugin in rust and I would like to use for example conrod for GUI but the host application only gives me a void * as a parent window.

This change would allow me (and others) to embed their rust development into other applications.

If you think this is interesting I can look into this issue (for windows at least)

Since winit is already using CreateWindowEx I think it is just a matter of API design.
I don't know how this works for other platforms.

**Comment by tomaka** [comment]
This needs to be done for Servo anyway.
Since the concept of a parent window doesn't exist everywhere, it must be done with the platform-specific builder.

**Comment by francesca64** [comment]
Closing in light of #96 + #159
